package com.bill99.mam.platform.controller.web.modelattribute;

import java.util.Date;

import com.bill99.mam.platform.common.enumeration.OrderStatusEnum;
import com.bill99.mam.platform.common.util.AmountUtil;

import lombok.Data;

@Data
public class OrderProductItemVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.ORDER_DETAIL_NO
     *
     * @mbg.generated
     */
    private Long orderDetailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PRODUCT_TAG
     *
     * @mbg.generated
     */
    private Long productTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PRODUCT_NAME
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PRODUCT_NUM
     *
     * @mbg.generated
     */
    private Long productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PRODUCT_PRICE
     *
     * @mbg.generated
     */
    private Long productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.LEDGER_RATE
     *
     * @mbg.generated
     */
    private Integer ledgerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PRODUCT_CATEGORY
     *
     * @mbg.generated
     */
    private String productCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PRODUCT_DESC
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.ORDER_STATUS
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitems.PAY_STATUS
     *
     * @mbg.generated
     */
    private Integer payStatus;
    
    private String merchantName;
    private String orderId;

    /**
     * 格式化orderAmount
     * 请勿删除
     * @return
     */
    public String getProductPriceFormat() {
    	String productPrice = null;
    	try {
    		productPrice = AmountUtil.changeF2Y(this.productPrice);
    	} catch (Exception e) {
    		
    	}
    	return productPrice;
    }
    
    /**
     * 订单状态
     * @return
     */
    public String getOrderStatusDesc() {
    	if (null != this.orderStatus) {
    		OrderStatusEnum e = OrderStatusEnum.get(this.orderStatus);
    		if (null != e) {
    			return e.desc();
    		}
    	}
    	return String.valueOf(this.orderStatus);
    }
}