package com.bill99.mam.platform.controller.web.modelattribute;

import com.bill99.mam.platform.common.enumeration.OrderStatusEnum;
import com.bill99.mam.platform.common.enumeration.OrderTypeEnum;
import com.bill99.mam.platform.common.util.AmountUtil;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;

import java.text.SimpleDateFormat;
import java.util.Date;
@Data
public class OrderVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.UID
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.PAYEE_UID
     *
     * @mbg.generated
     */
    private Long payeeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.ORDER_AMOUNT
     *
     * @mbg.generated
     */
    private Long orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.PAY_AMOUNT
     *
     * @mbg.generated
     */
    private Long payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.REFUND_AMOUNT
     *
     * @mbg.generated
     */
    private Long refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.ACTUAL_AMOUNT
     *
     * @mbg.generated
     */
    private Long actualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.TRADE_FEE
     *
     * @mbg.generated
     */
    private Long tradeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.IS_PLATFORM_PAY_FEE
     *
     * @mbg.generated
     */
    private Integer isPlatformPayFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.BILL_ORDER_NO
     *
     * @mbg.generated
     */
    private String billOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.TRADE_NO
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.FUNCTION_CODE
     *
     * @mbg.generated
     */
    private Integer functionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.SHARING_DATA
     *
     * @mbg.generated
     */
    private String sharingData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.FEE_MODE
     *
     * @mbg.generated
     */
    private Integer feeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.PAY_MODE
     *
     * @mbg.generated
     */
    private Integer payMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.PAY_STATUS
     *
     * @mbg.generated
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.ORDER_STATUS
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.SETTLE_PERIOD
     *
     * @mbg.generated
     */
    private String settlePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.TXN_BEGIN_TIME
     *
     * @mbg.generated
     */
    private Date txnBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.TXN_END_TIME
     *
     * @mbg.generated
     */
    private Date txnEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.TXN_EXPIRE_TIME
     *
     * @mbg.generated
     */
    private Date txnExpireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.MEMBER_BANK_ACCT_ID
     *
     * @mbg.generated
     */
    private String memberBankAcctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.CURRENCY_CODE
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.AUTH_CODE
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.ORDER_TYPE
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.PAY_TYPE
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.IS_ASSURED
     *
     * @mbg.generated
     */
    private Integer isAssured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.BG_URL
     *
     * @mbg.generated
     */
    private String bgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.STL_DATE
     *
     * @mbg.generated
     */
    private Date stlDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.PAY_URL
     *
     * @mbg.generated
     */
    private String payUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.SECURE_TYPE
     *
     * @mbg.generated
     */
    private Integer secureType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.DATA_MAP
     *
     * @mbg.generated
     */
    private String dataMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;
    private boolean show;
    /**
     * 转换orderType
     * 请勿删除
     * @return
     */
    public String getOrderTypeDesc() {
    	if (StringUtils.isNotBlank(this.orderType)) {
    		OrderTypeEnum e = OrderTypeEnum.getOrderTypeEnum(new Integer(this.orderType));
    		if (null != e) {
    			return e.desc();
    		}
    	}
    	return this.orderType;
    }
    
    /**
     * 转换orderType
     * 请勿删除
     * @return
     */
    public String getOrderStatusDesc() {
    	if (null != this.orderStatus) {
    		OrderStatusEnum e = OrderStatusEnum.get(this.orderStatus);
    		if (null != e) {
    			return e.desc();
    		}
    	}
    	return String.valueOf(this.orderStatus);
    }

    /**
     * 格式化orderAmount
     * 请勿删除
     * @return
     */
    public String getOrderAmountFormat() {
    	String orderAmount = null;
    	try {
    		orderAmount = AmountUtil.changeF2Y(String.valueOf(this.orderAmount));
    	} catch (Exception e) {
    		
    	}
    	return orderAmount;
    }
    
    public String getTxnBeginTimeFormat() {
    	if (null != txnBeginTime) {
    		return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(txnBeginTime);
    	}
    	return null;
    }

    public boolean isShow() {
        return show;
    }

    public void setShow(boolean show) {
        this.show = show;
    }
}