package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.platform_id
     *
     * @mbg.generated
     */
    private Long platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.customer_type
     *
     * @mbg.generated
     */
    private Integer customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.login_id
     *
     * @mbg.generated
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.login_type
     *
     * @mbg.generated
     */
    private Integer loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.idCard_Number
     *
     * @mbg.generated
     */
    private String idcardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_customer.idCard_Type
     *
     * @mbg.generated
     */
    private Integer idcardType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.id
     *
     * @return the value of t_mock_customer.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.id
     *
     * @param id the value for t_mock_customer.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.platform_id
     *
     * @return the value of t_mock_customer.platform_id
     *
     * @mbg.generated
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.platform_id
     *
     * @param platformId the value for t_mock_customer.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.customer_type
     *
     * @return the value of t_mock_customer.customer_type
     *
     * @mbg.generated
     */
    public Integer getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.customer_type
     *
     * @param customerType the value for t_mock_customer.customer_type
     *
     * @mbg.generated
     */
    public void setCustomerType(Integer customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.login_id
     *
     * @return the value of t_mock_customer.login_id
     *
     * @mbg.generated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.login_id
     *
     * @param loginId the value for t_mock_customer.login_id
     *
     * @mbg.generated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.login_type
     *
     * @return the value of t_mock_customer.login_type
     *
     * @mbg.generated
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.login_type
     *
     * @param loginType the value for t_mock_customer.login_type
     *
     * @mbg.generated
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.name
     *
     * @return the value of t_mock_customer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.name
     *
     * @param name the value for t_mock_customer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.status
     *
     * @return the value of t_mock_customer.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.status
     *
     * @param status the value for t_mock_customer.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.update_time
     *
     * @return the value of t_mock_customer.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.update_time
     *
     * @param updateTime the value for t_mock_customer.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.create_time
     *
     * @return the value of t_mock_customer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.create_time
     *
     * @param createTime the value for t_mock_customer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.idCard_Number
     *
     * @return the value of t_mock_customer.idCard_Number
     *
     * @mbg.generated
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.idCard_Number
     *
     * @param idcardNumber the value for t_mock_customer.idCard_Number
     *
     * @mbg.generated
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_customer.idCard_Type
     *
     * @return the value of t_mock_customer.idCard_Type
     *
     * @mbg.generated
     */
    public Integer getIdcardType() {
        return idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_customer.idCard_Type
     *
     * @param idcardType the value for t_mock_customer.idCard_Type
     *
     * @mbg.generated
     */
    public void setIdcardType(Integer idcardType) {
        this.idcardType = idcardType;
    }
}