package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class LedgerAcctConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.LEDGER_ACCT_TYPE
     *
     * @mbg.generated
     */
    private Integer ledgerAcctType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.GOODS_ID
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.RATE
     *
     * @mbg.generated
     */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.SHARING_TYPE
     *
     * @mbg.generated
     */
    private Integer sharingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_ledger_acct_config.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.ID
     *
     * @return the value of t_mock_ledger_acct_config.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.ID
     *
     * @param id the value for t_mock_ledger_acct_config.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.LEDGER_ACCT_TYPE
     *
     * @return the value of t_mock_ledger_acct_config.LEDGER_ACCT_TYPE
     *
     * @mbg.generated
     */
    public Integer getLedgerAcctType() {
        return ledgerAcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.LEDGER_ACCT_TYPE
     *
     * @param ledgerAcctType the value for t_mock_ledger_acct_config.LEDGER_ACCT_TYPE
     *
     * @mbg.generated
     */
    public void setLedgerAcctType(Integer ledgerAcctType) {
        this.ledgerAcctType = ledgerAcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.GOODS_ID
     *
     * @return the value of t_mock_ledger_acct_config.GOODS_ID
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.GOODS_ID
     *
     * @param goodsId the value for t_mock_ledger_acct_config.GOODS_ID
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.CUSTOMER_ID
     *
     * @return the value of t_mock_ledger_acct_config.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.CUSTOMER_ID
     *
     * @param customerId the value for t_mock_ledger_acct_config.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.RATE
     *
     * @return the value of t_mock_ledger_acct_config.RATE
     *
     * @mbg.generated
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.RATE
     *
     * @param rate the value for t_mock_ledger_acct_config.RATE
     *
     * @mbg.generated
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.SHARING_TYPE
     *
     * @return the value of t_mock_ledger_acct_config.SHARING_TYPE
     *
     * @mbg.generated
     */
    public Integer getSharingType() {
        return sharingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.SHARING_TYPE
     *
     * @param sharingType the value for t_mock_ledger_acct_config.SHARING_TYPE
     *
     * @mbg.generated
     */
    public void setSharingType(Integer sharingType) {
        this.sharingType = sharingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.CREATE_TIME
     *
     * @return the value of t_mock_ledger_acct_config.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.CREATE_TIME
     *
     * @param createTime the value for t_mock_ledger_acct_config.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_ledger_acct_config.UPDATE_TIME
     *
     * @return the value of t_mock_ledger_acct_config.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_ledger_acct_config.UPDATE_TIME
     *
     * @param updateTime the value for t_mock_ledger_acct_config.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}