package com.bill99.mam.platform.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderProductItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public OrderProductItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoIsNull() {
            addCriterion("order_detail_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoIsNotNull() {
            addCriterion("order_detail_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoEqualTo(Long value) {
            addCriterion("order_detail_no =", value, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoNotEqualTo(Long value) {
            addCriterion("order_detail_no <>", value, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoGreaterThan(Long value) {
            addCriterion("order_detail_no >", value, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoGreaterThanOrEqualTo(Long value) {
            addCriterion("order_detail_no >=", value, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoLessThan(Long value) {
            addCriterion("order_detail_no <", value, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoLessThanOrEqualTo(Long value) {
            addCriterion("order_detail_no <=", value, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoIn(List<Long> values) {
            addCriterion("order_detail_no in", values, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoNotIn(List<Long> values) {
            addCriterion("order_detail_no not in", values, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoBetween(Long value1, Long value2) {
            addCriterion("order_detail_no between", value1, value2, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andOrderDetailNoNotBetween(Long value1, Long value2) {
            addCriterion("order_detail_no not between", value1, value2, "orderDetailNo");
            return (Criteria) this;
        }

        public Criteria andProductTagIsNull() {
            addCriterion("product_tag is null");
            return (Criteria) this;
        }

        public Criteria andProductTagIsNotNull() {
            addCriterion("product_tag is not null");
            return (Criteria) this;
        }

        public Criteria andProductTagEqualTo(Long value) {
            addCriterion("product_tag =", value, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagNotEqualTo(Long value) {
            addCriterion("product_tag <>", value, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagGreaterThan(Long value) {
            addCriterion("product_tag >", value, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagGreaterThanOrEqualTo(Long value) {
            addCriterion("product_tag >=", value, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagLessThan(Long value) {
            addCriterion("product_tag <", value, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagLessThanOrEqualTo(Long value) {
            addCriterion("product_tag <=", value, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagIn(List<Long> values) {
            addCriterion("product_tag in", values, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagNotIn(List<Long> values) {
            addCriterion("product_tag not in", values, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagBetween(Long value1, Long value2) {
            addCriterion("product_tag between", value1, value2, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductTagNotBetween(Long value1, Long value2) {
            addCriterion("product_tag not between", value1, value2, "productTag");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNumIsNull() {
            addCriterion("product_num is null");
            return (Criteria) this;
        }

        public Criteria andProductNumIsNotNull() {
            addCriterion("product_num is not null");
            return (Criteria) this;
        }

        public Criteria andProductNumEqualTo(Long value) {
            addCriterion("product_num =", value, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumNotEqualTo(Long value) {
            addCriterion("product_num <>", value, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumGreaterThan(Long value) {
            addCriterion("product_num >", value, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumGreaterThanOrEqualTo(Long value) {
            addCriterion("product_num >=", value, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumLessThan(Long value) {
            addCriterion("product_num <", value, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumLessThanOrEqualTo(Long value) {
            addCriterion("product_num <=", value, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumIn(List<Long> values) {
            addCriterion("product_num in", values, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumNotIn(List<Long> values) {
            addCriterion("product_num not in", values, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumBetween(Long value1, Long value2) {
            addCriterion("product_num between", value1, value2, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductNumNotBetween(Long value1, Long value2) {
            addCriterion("product_num not between", value1, value2, "productNum");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(Long value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(Long value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(Long value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(Long value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(Long value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<Long> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<Long> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(Long value1, Long value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(Long value1, Long value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andLedgerRateIsNull() {
            addCriterion("ledger_rate is null");
            return (Criteria) this;
        }

        public Criteria andLedgerRateIsNotNull() {
            addCriterion("ledger_rate is not null");
            return (Criteria) this;
        }

        public Criteria andLedgerRateEqualTo(Integer value) {
            addCriterion("ledger_rate =", value, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateNotEqualTo(Integer value) {
            addCriterion("ledger_rate <>", value, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateGreaterThan(Integer value) {
            addCriterion("ledger_rate >", value, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("ledger_rate >=", value, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateLessThan(Integer value) {
            addCriterion("ledger_rate <", value, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateLessThanOrEqualTo(Integer value) {
            addCriterion("ledger_rate <=", value, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateIn(List<Integer> values) {
            addCriterion("ledger_rate in", values, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateNotIn(List<Integer> values) {
            addCriterion("ledger_rate not in", values, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateBetween(Integer value1, Integer value2) {
            addCriterion("ledger_rate between", value1, value2, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andLedgerRateNotBetween(Integer value1, Integer value2) {
            addCriterion("ledger_rate not between", value1, value2, "ledgerRate");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountIsNull() {
            addCriterion("merchant_ledger_amount is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountIsNotNull() {
            addCriterion("merchant_ledger_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountEqualTo(Long value) {
            addCriterion("merchant_ledger_amount =", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountNotEqualTo(Long value) {
            addCriterion("merchant_ledger_amount <>", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountGreaterThan(Long value) {
            addCriterion("merchant_ledger_amount >", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("merchant_ledger_amount >=", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountLessThan(Long value) {
            addCriterion("merchant_ledger_amount <", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountLessThanOrEqualTo(Long value) {
            addCriterion("merchant_ledger_amount <=", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountIn(List<Long> values) {
            addCriterion("merchant_ledger_amount in", values, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountNotIn(List<Long> values) {
            addCriterion("merchant_ledger_amount not in", values, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountBetween(Long value1, Long value2) {
            addCriterion("merchant_ledger_amount between", value1, value2, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountNotBetween(Long value1, Long value2) {
            addCriterion("merchant_ledger_amount not between", value1, value2, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountIsNull() {
            addCriterion("platform_ledger_amount is null");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountIsNotNull() {
            addCriterion("platform_ledger_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountEqualTo(Long value) {
            addCriterion("platform_ledger_amount =", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountNotEqualTo(Long value) {
            addCriterion("platform_ledger_amount <>", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountGreaterThan(Long value) {
            addCriterion("platform_ledger_amount >", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("platform_ledger_amount >=", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountLessThan(Long value) {
            addCriterion("platform_ledger_amount <", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountLessThanOrEqualTo(Long value) {
            addCriterion("platform_ledger_amount <=", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountIn(List<Long> values) {
            addCriterion("platform_ledger_amount in", values, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountNotIn(List<Long> values) {
            addCriterion("platform_ledger_amount not in", values, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountBetween(Long value1, Long value2) {
            addCriterion("platform_ledger_amount between", value1, value2, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountNotBetween(Long value1, Long value2) {
            addCriterion("platform_ledger_amount not between", value1, value2, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIsNull() {
            addCriterion("product_category is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIsNotNull() {
            addCriterion("product_category is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryEqualTo(String value) {
            addCriterion("product_category =", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotEqualTo(String value) {
            addCriterion("product_category <>", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryGreaterThan(String value) {
            addCriterion("product_category >", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("product_category >=", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLessThan(String value) {
            addCriterion("product_category <", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLessThanOrEqualTo(String value) {
            addCriterion("product_category <=", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLike(String value) {
            addCriterion("product_category like", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotLike(String value) {
            addCriterion("product_category not like", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIn(List<String> values) {
            addCriterion("product_category in", values, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotIn(List<String> values) {
            addCriterion("product_category not in", values, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryBetween(String value1, String value2) {
            addCriterion("product_category between", value1, value2, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotBetween(String value1, String value2) {
            addCriterion("product_category not between", value1, value2, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductDescIsNull() {
            addCriterion("product_desc is null");
            return (Criteria) this;
        }

        public Criteria andProductDescIsNotNull() {
            addCriterion("product_desc is not null");
            return (Criteria) this;
        }

        public Criteria andProductDescEqualTo(String value) {
            addCriterion("product_desc =", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotEqualTo(String value) {
            addCriterion("product_desc <>", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescGreaterThan(String value) {
            addCriterion("product_desc >", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescGreaterThanOrEqualTo(String value) {
            addCriterion("product_desc >=", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLessThan(String value) {
            addCriterion("product_desc <", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLessThanOrEqualTo(String value) {
            addCriterion("product_desc <=", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLike(String value) {
            addCriterion("product_desc like", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotLike(String value) {
            addCriterion("product_desc not like", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescIn(List<String> values) {
            addCriterion("product_desc in", values, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotIn(List<String> values) {
            addCriterion("product_desc not in", values, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescBetween(String value1, String value2) {
            addCriterion("product_desc between", value1, value2, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotBetween(String value1, String value2) {
            addCriterion("product_desc not between", value1, value2, "productDesc");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("pay_status is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(Integer value) {
            addCriterion("pay_status =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(Integer value) {
            addCriterion("pay_status <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(Integer value) {
            addCriterion("pay_status >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_status >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(Integer value) {
            addCriterion("pay_status <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("pay_status <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<Integer> values) {
            addCriterion("pay_status in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<Integer> values) {
            addCriterion("pay_status not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(Integer value1, Integer value2) {
            addCriterion("pay_status between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_status not between", value1, value2, "payStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}