package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.payee_uid
     *
     * @mbg.generated
     */
    private Long payeeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.order_amount
     *
     * @mbg.generated
     */
    private Long orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.pay_amount
     *
     * @mbg.generated
     */
    private Long payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.refund_amount
     *
     * @mbg.generated
     */
    private Long refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.actual_amount
     *
     * @mbg.generated
     */
    private Long actualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.trade_fee
     *
     * @mbg.generated
     */
    private Long tradeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.is_platform_pay_fee
     *
     * @mbg.generated
     */
    private Integer isPlatformPayFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.bill_order_no
     *
     * @mbg.generated
     */
    private String billOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.trade_no
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.function_code
     *
     * @mbg.generated
     */
    private Integer functionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.sharing_data
     *
     * @mbg.generated
     */
    private String sharingData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.fee_mode
     *
     * @mbg.generated
     */
    private Integer feeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.pay_mode
     *
     * @mbg.generated
     */
    private Integer payMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.pay_status
     *
     * @mbg.generated
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.settle_period
     *
     * @mbg.generated
     */
    private String settlePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.txn_begin_time
     *
     * @mbg.generated
     */
    private Date txnBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.txn_end_time
     *
     * @mbg.generated
     */
    private Date txnEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.txn_expire_time
     *
     * @mbg.generated
     */
    private Date txnExpireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.member_bank_acct_id
     *
     * @mbg.generated
     */
    private String memberBankAcctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.auth_code
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.is_assured
     *
     * @mbg.generated
     */
    private Integer isAssured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.bg_url
     *
     * @mbg.generated
     */
    private String bgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.stl_date
     *
     * @mbg.generated
     */
    private Date stlDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.pay_url
     *
     * @mbg.generated
     */
    private String payUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.secure_type
     *
     * @mbg.generated
     */
    private Integer secureType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.resp_code
     *
     * @mbg.generated
     */
    private String respCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.resp_msg
     *
     * @mbg.generated
     */
    private String respMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.data_map
     *
     * @mbg.generated
     */
    private String dataMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.id
     *
     * @return the value of t_mock_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.id
     *
     * @param id the value for t_mock_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.uid
     *
     * @return the value of t_mock_order.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.uid
     *
     * @param uid the value for t_mock_order.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.payee_uid
     *
     * @return the value of t_mock_order.payee_uid
     *
     * @mbg.generated
     */
    public Long getPayeeUid() {
        return payeeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.payee_uid
     *
     * @param payeeUid the value for t_mock_order.payee_uid
     *
     * @mbg.generated
     */
    public void setPayeeUid(Long payeeUid) {
        this.payeeUid = payeeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.order_amount
     *
     * @return the value of t_mock_order.order_amount
     *
     * @mbg.generated
     */
    public Long getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.order_amount
     *
     * @param orderAmount the value for t_mock_order.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.pay_amount
     *
     * @return the value of t_mock_order.pay_amount
     *
     * @mbg.generated
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.pay_amount
     *
     * @param payAmount the value for t_mock_order.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.refund_amount
     *
     * @return the value of t_mock_order.refund_amount
     *
     * @mbg.generated
     */
    public Long getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.refund_amount
     *
     * @param refundAmount the value for t_mock_order.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(Long refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.actual_amount
     *
     * @return the value of t_mock_order.actual_amount
     *
     * @mbg.generated
     */
    public Long getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.actual_amount
     *
     * @param actualAmount the value for t_mock_order.actual_amount
     *
     * @mbg.generated
     */
    public void setActualAmount(Long actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.trade_fee
     *
     * @return the value of t_mock_order.trade_fee
     *
     * @mbg.generated
     */
    public Long getTradeFee() {
        return tradeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.trade_fee
     *
     * @param tradeFee the value for t_mock_order.trade_fee
     *
     * @mbg.generated
     */
    public void setTradeFee(Long tradeFee) {
        this.tradeFee = tradeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.is_platform_pay_fee
     *
     * @return the value of t_mock_order.is_platform_pay_fee
     *
     * @mbg.generated
     */
    public Integer getIsPlatformPayFee() {
        return isPlatformPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.is_platform_pay_fee
     *
     * @param isPlatformPayFee the value for t_mock_order.is_platform_pay_fee
     *
     * @mbg.generated
     */
    public void setIsPlatformPayFee(Integer isPlatformPayFee) {
        this.isPlatformPayFee = isPlatformPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.bill_order_no
     *
     * @return the value of t_mock_order.bill_order_no
     *
     * @mbg.generated
     */
    public String getBillOrderNo() {
        return billOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.bill_order_no
     *
     * @param billOrderNo the value for t_mock_order.bill_order_no
     *
     * @mbg.generated
     */
    public void setBillOrderNo(String billOrderNo) {
        this.billOrderNo = billOrderNo == null ? null : billOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.trade_no
     *
     * @return the value of t_mock_order.trade_no
     *
     * @mbg.generated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.trade_no
     *
     * @param tradeNo the value for t_mock_order.trade_no
     *
     * @mbg.generated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.function_code
     *
     * @return the value of t_mock_order.function_code
     *
     * @mbg.generated
     */
    public Integer getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.function_code
     *
     * @param functionCode the value for t_mock_order.function_code
     *
     * @mbg.generated
     */
    public void setFunctionCode(Integer functionCode) {
        this.functionCode = functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.sharing_data
     *
     * @return the value of t_mock_order.sharing_data
     *
     * @mbg.generated
     */
    public String getSharingData() {
        return sharingData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.sharing_data
     *
     * @param sharingData the value for t_mock_order.sharing_data
     *
     * @mbg.generated
     */
    public void setSharingData(String sharingData) {
        this.sharingData = sharingData == null ? null : sharingData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.fee_mode
     *
     * @return the value of t_mock_order.fee_mode
     *
     * @mbg.generated
     */
    public Integer getFeeMode() {
        return feeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.fee_mode
     *
     * @param feeMode the value for t_mock_order.fee_mode
     *
     * @mbg.generated
     */
    public void setFeeMode(Integer feeMode) {
        this.feeMode = feeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.pay_mode
     *
     * @return the value of t_mock_order.pay_mode
     *
     * @mbg.generated
     */
    public Integer getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.pay_mode
     *
     * @param payMode the value for t_mock_order.pay_mode
     *
     * @mbg.generated
     */
    public void setPayMode(Integer payMode) {
        this.payMode = payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.pay_status
     *
     * @return the value of t_mock_order.pay_status
     *
     * @mbg.generated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.pay_status
     *
     * @param payStatus the value for t_mock_order.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.order_status
     *
     * @return the value of t_mock_order.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.order_status
     *
     * @param orderStatus the value for t_mock_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.settle_period
     *
     * @return the value of t_mock_order.settle_period
     *
     * @mbg.generated
     */
    public String getSettlePeriod() {
        return settlePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.settle_period
     *
     * @param settlePeriod the value for t_mock_order.settle_period
     *
     * @mbg.generated
     */
    public void setSettlePeriod(String settlePeriod) {
        this.settlePeriod = settlePeriod == null ? null : settlePeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.txn_begin_time
     *
     * @return the value of t_mock_order.txn_begin_time
     *
     * @mbg.generated
     */
    public Date getTxnBeginTime() {
        return txnBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.txn_begin_time
     *
     * @param txnBeginTime the value for t_mock_order.txn_begin_time
     *
     * @mbg.generated
     */
    public void setTxnBeginTime(Date txnBeginTime) {
        this.txnBeginTime = txnBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.txn_end_time
     *
     * @return the value of t_mock_order.txn_end_time
     *
     * @mbg.generated
     */
    public Date getTxnEndTime() {
        return txnEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.txn_end_time
     *
     * @param txnEndTime the value for t_mock_order.txn_end_time
     *
     * @mbg.generated
     */
    public void setTxnEndTime(Date txnEndTime) {
        this.txnEndTime = txnEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.txn_expire_time
     *
     * @return the value of t_mock_order.txn_expire_time
     *
     * @mbg.generated
     */
    public Date getTxnExpireTime() {
        return txnExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.txn_expire_time
     *
     * @param txnExpireTime the value for t_mock_order.txn_expire_time
     *
     * @mbg.generated
     */
    public void setTxnExpireTime(Date txnExpireTime) {
        this.txnExpireTime = txnExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.member_bank_acct_id
     *
     * @return the value of t_mock_order.member_bank_acct_id
     *
     * @mbg.generated
     */
    public String getMemberBankAcctId() {
        return memberBankAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.member_bank_acct_id
     *
     * @param memberBankAcctId the value for t_mock_order.member_bank_acct_id
     *
     * @mbg.generated
     */
    public void setMemberBankAcctId(String memberBankAcctId) {
        this.memberBankAcctId = memberBankAcctId == null ? null : memberBankAcctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.currency_code
     *
     * @return the value of t_mock_order.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.currency_code
     *
     * @param currencyCode the value for t_mock_order.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.auth_code
     *
     * @return the value of t_mock_order.auth_code
     *
     * @mbg.generated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.auth_code
     *
     * @param authCode the value for t_mock_order.auth_code
     *
     * @mbg.generated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.order_type
     *
     * @return the value of t_mock_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.order_type
     *
     * @param orderType the value for t_mock_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.pay_type
     *
     * @return the value of t_mock_order.pay_type
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.pay_type
     *
     * @param payType the value for t_mock_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.is_assured
     *
     * @return the value of t_mock_order.is_assured
     *
     * @mbg.generated
     */
    public Integer getIsAssured() {
        return isAssured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.is_assured
     *
     * @param isAssured the value for t_mock_order.is_assured
     *
     * @mbg.generated
     */
    public void setIsAssured(Integer isAssured) {
        this.isAssured = isAssured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.bg_url
     *
     * @return the value of t_mock_order.bg_url
     *
     * @mbg.generated
     */
    public String getBgUrl() {
        return bgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.bg_url
     *
     * @param bgUrl the value for t_mock_order.bg_url
     *
     * @mbg.generated
     */
    public void setBgUrl(String bgUrl) {
        this.bgUrl = bgUrl == null ? null : bgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.stl_date
     *
     * @return the value of t_mock_order.stl_date
     *
     * @mbg.generated
     */
    public Date getStlDate() {
        return stlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.stl_date
     *
     * @param stlDate the value for t_mock_order.stl_date
     *
     * @mbg.generated
     */
    public void setStlDate(Date stlDate) {
        this.stlDate = stlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.pay_url
     *
     * @return the value of t_mock_order.pay_url
     *
     * @mbg.generated
     */
    public String getPayUrl() {
        return payUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.pay_url
     *
     * @param payUrl the value for t_mock_order.pay_url
     *
     * @mbg.generated
     */
    public void setPayUrl(String payUrl) {
        this.payUrl = payUrl == null ? null : payUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.secure_type
     *
     * @return the value of t_mock_order.secure_type
     *
     * @mbg.generated
     */
    public Integer getSecureType() {
        return secureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.secure_type
     *
     * @param secureType the value for t_mock_order.secure_type
     *
     * @mbg.generated
     */
    public void setSecureType(Integer secureType) {
        this.secureType = secureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.resp_code
     *
     * @return the value of t_mock_order.resp_code
     *
     * @mbg.generated
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.resp_code
     *
     * @param respCode the value for t_mock_order.resp_code
     *
     * @mbg.generated
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode == null ? null : respCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.resp_msg
     *
     * @return the value of t_mock_order.resp_msg
     *
     * @mbg.generated
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.resp_msg
     *
     * @param respMsg the value for t_mock_order.resp_msg
     *
     * @mbg.generated
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg == null ? null : respMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.memo
     *
     * @return the value of t_mock_order.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.memo
     *
     * @param memo the value for t_mock_order.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.data_map
     *
     * @return the value of t_mock_order.data_map
     *
     * @mbg.generated
     */
    public String getDataMap() {
        return dataMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.data_map
     *
     * @param dataMap the value for t_mock_order.data_map
     *
     * @mbg.generated
     */
    public void setDataMap(String dataMap) {
        this.dataMap = dataMap == null ? null : dataMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.update_time
     *
     * @return the value of t_mock_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.update_time
     *
     * @param updateTime the value for t_mock_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order.create_time
     *
     * @return the value of t_mock_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order.create_time
     *
     * @param createTime the value for t_mock_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}