package com.bill99.mam.platform.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIsNull() {
            addCriterion("payee_uid is null");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIsNotNull() {
            addCriterion("payee_uid is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeUidEqualTo(Long value) {
            addCriterion("payee_uid =", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotEqualTo(Long value) {
            addCriterion("payee_uid <>", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidGreaterThan(Long value) {
            addCriterion("payee_uid >", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidGreaterThanOrEqualTo(Long value) {
            addCriterion("payee_uid >=", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLessThan(Long value) {
            addCriterion("payee_uid <", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLessThanOrEqualTo(Long value) {
            addCriterion("payee_uid <=", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIn(List<Long> values) {
            addCriterion("payee_uid in", values, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotIn(List<Long> values) {
            addCriterion("payee_uid not in", values, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidBetween(Long value1, Long value2) {
            addCriterion("payee_uid between", value1, value2, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotBetween(Long value1, Long value2) {
            addCriterion("payee_uid not between", value1, value2, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNull() {
            addCriterion("order_amount is null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNotNull() {
            addCriterion("order_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountEqualTo(Long value) {
            addCriterion("order_amount =", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotEqualTo(Long value) {
            addCriterion("order_amount <>", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThan(Long value) {
            addCriterion("order_amount >", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("order_amount >=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThan(Long value) {
            addCriterion("order_amount <", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThanOrEqualTo(Long value) {
            addCriterion("order_amount <=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIn(List<Long> values) {
            addCriterion("order_amount in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotIn(List<Long> values) {
            addCriterion("order_amount not in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountBetween(Long value1, Long value2) {
            addCriterion("order_amount between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotBetween(Long value1, Long value2) {
            addCriterion("order_amount not between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNull() {
            addCriterion("pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNotNull() {
            addCriterion("pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPayAmountEqualTo(Long value) {
            addCriterion("pay_amount =", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotEqualTo(Long value) {
            addCriterion("pay_amount <>", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThan(Long value) {
            addCriterion("pay_amount >", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_amount >=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThan(Long value) {
            addCriterion("pay_amount <", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThanOrEqualTo(Long value) {
            addCriterion("pay_amount <=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIn(List<Long> values) {
            addCriterion("pay_amount in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotIn(List<Long> values) {
            addCriterion("pay_amount not in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountBetween(Long value1, Long value2) {
            addCriterion("pay_amount between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotBetween(Long value1, Long value2) {
            addCriterion("pay_amount not between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNull() {
            addCriterion("refund_amount is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNotNull() {
            addCriterion("refund_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountEqualTo(Long value) {
            addCriterion("refund_amount =", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotEqualTo(Long value) {
            addCriterion("refund_amount <>", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThan(Long value) {
            addCriterion("refund_amount >", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("refund_amount >=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThan(Long value) {
            addCriterion("refund_amount <", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThanOrEqualTo(Long value) {
            addCriterion("refund_amount <=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIn(List<Long> values) {
            addCriterion("refund_amount in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotIn(List<Long> values) {
            addCriterion("refund_amount not in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountBetween(Long value1, Long value2) {
            addCriterion("refund_amount between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotBetween(Long value1, Long value2) {
            addCriterion("refund_amount not between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountIsNull() {
            addCriterion("actual_amount is null");
            return (Criteria) this;
        }

        public Criteria andActualAmountIsNotNull() {
            addCriterion("actual_amount is not null");
            return (Criteria) this;
        }

        public Criteria andActualAmountEqualTo(Long value) {
            addCriterion("actual_amount =", value, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountNotEqualTo(Long value) {
            addCriterion("actual_amount <>", value, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountGreaterThan(Long value) {
            addCriterion("actual_amount >", value, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("actual_amount >=", value, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountLessThan(Long value) {
            addCriterion("actual_amount <", value, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountLessThanOrEqualTo(Long value) {
            addCriterion("actual_amount <=", value, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountIn(List<Long> values) {
            addCriterion("actual_amount in", values, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountNotIn(List<Long> values) {
            addCriterion("actual_amount not in", values, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountBetween(Long value1, Long value2) {
            addCriterion("actual_amount between", value1, value2, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andActualAmountNotBetween(Long value1, Long value2) {
            addCriterion("actual_amount not between", value1, value2, "actualAmount");
            return (Criteria) this;
        }

        public Criteria andTradeFeeIsNull() {
            addCriterion("trade_fee is null");
            return (Criteria) this;
        }

        public Criteria andTradeFeeIsNotNull() {
            addCriterion("trade_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTradeFeeEqualTo(Long value) {
            addCriterion("trade_fee =", value, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeNotEqualTo(Long value) {
            addCriterion("trade_fee <>", value, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeGreaterThan(Long value) {
            addCriterion("trade_fee >", value, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeGreaterThanOrEqualTo(Long value) {
            addCriterion("trade_fee >=", value, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeLessThan(Long value) {
            addCriterion("trade_fee <", value, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeLessThanOrEqualTo(Long value) {
            addCriterion("trade_fee <=", value, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeIn(List<Long> values) {
            addCriterion("trade_fee in", values, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeNotIn(List<Long> values) {
            addCriterion("trade_fee not in", values, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeBetween(Long value1, Long value2) {
            addCriterion("trade_fee between", value1, value2, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andTradeFeeNotBetween(Long value1, Long value2) {
            addCriterion("trade_fee not between", value1, value2, "tradeFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeIsNull() {
            addCriterion("is_platform_pay_fee is null");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeIsNotNull() {
            addCriterion("is_platform_pay_fee is not null");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeEqualTo(Integer value) {
            addCriterion("is_platform_pay_fee =", value, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeNotEqualTo(Integer value) {
            addCriterion("is_platform_pay_fee <>", value, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeGreaterThan(Integer value) {
            addCriterion("is_platform_pay_fee >", value, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_platform_pay_fee >=", value, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeLessThan(Integer value) {
            addCriterion("is_platform_pay_fee <", value, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeLessThanOrEqualTo(Integer value) {
            addCriterion("is_platform_pay_fee <=", value, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeIn(List<Integer> values) {
            addCriterion("is_platform_pay_fee in", values, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeNotIn(List<Integer> values) {
            addCriterion("is_platform_pay_fee not in", values, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeBetween(Integer value1, Integer value2) {
            addCriterion("is_platform_pay_fee between", value1, value2, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andIsPlatformPayFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("is_platform_pay_fee not between", value1, value2, "isPlatformPayFee");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoIsNull() {
            addCriterion("bill_order_no is null");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoIsNotNull() {
            addCriterion("bill_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoEqualTo(String value) {
            addCriterion("bill_order_no =", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotEqualTo(String value) {
            addCriterion("bill_order_no <>", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoGreaterThan(String value) {
            addCriterion("bill_order_no >", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("bill_order_no >=", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoLessThan(String value) {
            addCriterion("bill_order_no <", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoLessThanOrEqualTo(String value) {
            addCriterion("bill_order_no <=", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoLike(String value) {
            addCriterion("bill_order_no like", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotLike(String value) {
            addCriterion("bill_order_no not like", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoIn(List<String> values) {
            addCriterion("bill_order_no in", values, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotIn(List<String> values) {
            addCriterion("bill_order_no not in", values, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoBetween(String value1, String value2) {
            addCriterion("bill_order_no between", value1, value2, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotBetween(String value1, String value2) {
            addCriterion("bill_order_no not between", value1, value2, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNull() {
            addCriterion("trade_no is null");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNotNull() {
            addCriterion("trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNoEqualTo(String value) {
            addCriterion("trade_no =", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotEqualTo(String value) {
            addCriterion("trade_no <>", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThan(String value) {
            addCriterion("trade_no >", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("trade_no >=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThan(String value) {
            addCriterion("trade_no <", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThanOrEqualTo(String value) {
            addCriterion("trade_no <=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLike(String value) {
            addCriterion("trade_no like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotLike(String value) {
            addCriterion("trade_no not like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIn(List<String> values) {
            addCriterion("trade_no in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotIn(List<String> values) {
            addCriterion("trade_no not in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoBetween(String value1, String value2) {
            addCriterion("trade_no between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotBetween(String value1, String value2) {
            addCriterion("trade_no not between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeIsNull() {
            addCriterion("function_code is null");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeIsNotNull() {
            addCriterion("function_code is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeEqualTo(Integer value) {
            addCriterion("function_code =", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotEqualTo(Integer value) {
            addCriterion("function_code <>", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeGreaterThan(Integer value) {
            addCriterion("function_code >", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("function_code >=", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeLessThan(Integer value) {
            addCriterion("function_code <", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeLessThanOrEqualTo(Integer value) {
            addCriterion("function_code <=", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeIn(List<Integer> values) {
            addCriterion("function_code in", values, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotIn(List<Integer> values) {
            addCriterion("function_code not in", values, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeBetween(Integer value1, Integer value2) {
            addCriterion("function_code between", value1, value2, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("function_code not between", value1, value2, "functionCode");
            return (Criteria) this;
        }

        public Criteria andSharingDataIsNull() {
            addCriterion("sharing_data is null");
            return (Criteria) this;
        }

        public Criteria andSharingDataIsNotNull() {
            addCriterion("sharing_data is not null");
            return (Criteria) this;
        }

        public Criteria andSharingDataEqualTo(String value) {
            addCriterion("sharing_data =", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotEqualTo(String value) {
            addCriterion("sharing_data <>", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataGreaterThan(String value) {
            addCriterion("sharing_data >", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataGreaterThanOrEqualTo(String value) {
            addCriterion("sharing_data >=", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataLessThan(String value) {
            addCriterion("sharing_data <", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataLessThanOrEqualTo(String value) {
            addCriterion("sharing_data <=", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataLike(String value) {
            addCriterion("sharing_data like", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotLike(String value) {
            addCriterion("sharing_data not like", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataIn(List<String> values) {
            addCriterion("sharing_data in", values, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotIn(List<String> values) {
            addCriterion("sharing_data not in", values, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataBetween(String value1, String value2) {
            addCriterion("sharing_data between", value1, value2, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotBetween(String value1, String value2) {
            addCriterion("sharing_data not between", value1, value2, "sharingData");
            return (Criteria) this;
        }

        public Criteria andFeeModeIsNull() {
            addCriterion("fee_mode is null");
            return (Criteria) this;
        }

        public Criteria andFeeModeIsNotNull() {
            addCriterion("fee_mode is not null");
            return (Criteria) this;
        }

        public Criteria andFeeModeEqualTo(Integer value) {
            addCriterion("fee_mode =", value, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeNotEqualTo(Integer value) {
            addCriterion("fee_mode <>", value, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeGreaterThan(Integer value) {
            addCriterion("fee_mode >", value, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fee_mode >=", value, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeLessThan(Integer value) {
            addCriterion("fee_mode <", value, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeLessThanOrEqualTo(Integer value) {
            addCriterion("fee_mode <=", value, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeIn(List<Integer> values) {
            addCriterion("fee_mode in", values, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeNotIn(List<Integer> values) {
            addCriterion("fee_mode not in", values, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeBetween(Integer value1, Integer value2) {
            addCriterion("fee_mode between", value1, value2, "feeMode");
            return (Criteria) this;
        }

        public Criteria andFeeModeNotBetween(Integer value1, Integer value2) {
            addCriterion("fee_mode not between", value1, value2, "feeMode");
            return (Criteria) this;
        }

        public Criteria andPayModeIsNull() {
            addCriterion("pay_mode is null");
            return (Criteria) this;
        }

        public Criteria andPayModeIsNotNull() {
            addCriterion("pay_mode is not null");
            return (Criteria) this;
        }

        public Criteria andPayModeEqualTo(Integer value) {
            addCriterion("pay_mode =", value, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeNotEqualTo(Integer value) {
            addCriterion("pay_mode <>", value, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeGreaterThan(Integer value) {
            addCriterion("pay_mode >", value, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_mode >=", value, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeLessThan(Integer value) {
            addCriterion("pay_mode <", value, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_mode <=", value, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeIn(List<Integer> values) {
            addCriterion("pay_mode in", values, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeNotIn(List<Integer> values) {
            addCriterion("pay_mode not in", values, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeBetween(Integer value1, Integer value2) {
            addCriterion("pay_mode between", value1, value2, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayModeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_mode not between", value1, value2, "payMode");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("pay_status is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(Integer value) {
            addCriterion("pay_status =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(Integer value) {
            addCriterion("pay_status <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(Integer value) {
            addCriterion("pay_status >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_status >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(Integer value) {
            addCriterion("pay_status <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("pay_status <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<Integer> values) {
            addCriterion("pay_status in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<Integer> values) {
            addCriterion("pay_status not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(Integer value1, Integer value2) {
            addCriterion("pay_status between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_status not between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIsNull() {
            addCriterion("settle_period is null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIsNotNull() {
            addCriterion("settle_period is not null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodEqualTo(String value) {
            addCriterion("settle_period =", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotEqualTo(String value) {
            addCriterion("settle_period <>", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodGreaterThan(String value) {
            addCriterion("settle_period >", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodGreaterThanOrEqualTo(String value) {
            addCriterion("settle_period >=", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLessThan(String value) {
            addCriterion("settle_period <", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLessThanOrEqualTo(String value) {
            addCriterion("settle_period <=", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLike(String value) {
            addCriterion("settle_period like", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotLike(String value) {
            addCriterion("settle_period not like", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIn(List<String> values) {
            addCriterion("settle_period in", values, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotIn(List<String> values) {
            addCriterion("settle_period not in", values, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodBetween(String value1, String value2) {
            addCriterion("settle_period between", value1, value2, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotBetween(String value1, String value2) {
            addCriterion("settle_period not between", value1, value2, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeIsNull() {
            addCriterion("txn_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeIsNotNull() {
            addCriterion("txn_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeEqualTo(Date value) {
            addCriterion("txn_begin_time =", value, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeNotEqualTo(Date value) {
            addCriterion("txn_begin_time <>", value, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeGreaterThan(Date value) {
            addCriterion("txn_begin_time >", value, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("txn_begin_time >=", value, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeLessThan(Date value) {
            addCriterion("txn_begin_time <", value, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("txn_begin_time <=", value, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeIn(List<Date> values) {
            addCriterion("txn_begin_time in", values, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeNotIn(List<Date> values) {
            addCriterion("txn_begin_time not in", values, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeBetween(Date value1, Date value2) {
            addCriterion("txn_begin_time between", value1, value2, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("txn_begin_time not between", value1, value2, "txnBeginTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeIsNull() {
            addCriterion("txn_end_time is null");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeIsNotNull() {
            addCriterion("txn_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeEqualTo(Date value) {
            addCriterion("txn_end_time =", value, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeNotEqualTo(Date value) {
            addCriterion("txn_end_time <>", value, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeGreaterThan(Date value) {
            addCriterion("txn_end_time >", value, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("txn_end_time >=", value, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeLessThan(Date value) {
            addCriterion("txn_end_time <", value, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("txn_end_time <=", value, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeIn(List<Date> values) {
            addCriterion("txn_end_time in", values, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeNotIn(List<Date> values) {
            addCriterion("txn_end_time not in", values, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeBetween(Date value1, Date value2) {
            addCriterion("txn_end_time between", value1, value2, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("txn_end_time not between", value1, value2, "txnEndTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeIsNull() {
            addCriterion("txn_expire_time is null");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeIsNotNull() {
            addCriterion("txn_expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeEqualTo(Date value) {
            addCriterion("txn_expire_time =", value, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeNotEqualTo(Date value) {
            addCriterion("txn_expire_time <>", value, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeGreaterThan(Date value) {
            addCriterion("txn_expire_time >", value, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("txn_expire_time >=", value, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeLessThan(Date value) {
            addCriterion("txn_expire_time <", value, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("txn_expire_time <=", value, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeIn(List<Date> values) {
            addCriterion("txn_expire_time in", values, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeNotIn(List<Date> values) {
            addCriterion("txn_expire_time not in", values, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeBetween(Date value1, Date value2) {
            addCriterion("txn_expire_time between", value1, value2, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andTxnExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("txn_expire_time not between", value1, value2, "txnExpireTime");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdIsNull() {
            addCriterion("member_bank_acct_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdIsNotNull() {
            addCriterion("member_bank_acct_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdEqualTo(String value) {
            addCriterion("member_bank_acct_id =", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdNotEqualTo(String value) {
            addCriterion("member_bank_acct_id <>", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdGreaterThan(String value) {
            addCriterion("member_bank_acct_id >", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdGreaterThanOrEqualTo(String value) {
            addCriterion("member_bank_acct_id >=", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdLessThan(String value) {
            addCriterion("member_bank_acct_id <", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdLessThanOrEqualTo(String value) {
            addCriterion("member_bank_acct_id <=", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdLike(String value) {
            addCriterion("member_bank_acct_id like", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdNotLike(String value) {
            addCriterion("member_bank_acct_id not like", value, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdIn(List<String> values) {
            addCriterion("member_bank_acct_id in", values, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdNotIn(List<String> values) {
            addCriterion("member_bank_acct_id not in", values, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdBetween(String value1, String value2) {
            addCriterion("member_bank_acct_id between", value1, value2, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andMemberBankAcctIdNotBetween(String value1, String value2) {
            addCriterion("member_bank_acct_id not between", value1, value2, "memberBankAcctId");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNull() {
            addCriterion("currency_code is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNotNull() {
            addCriterion("currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeEqualTo(String value) {
            addCriterion("currency_code =", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotEqualTo(String value) {
            addCriterion("currency_code <>", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThan(String value) {
            addCriterion("currency_code >", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("currency_code >=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThan(String value) {
            addCriterion("currency_code <", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("currency_code <=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLike(String value) {
            addCriterion("currency_code like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotLike(String value) {
            addCriterion("currency_code not like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIn(List<String> values) {
            addCriterion("currency_code in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotIn(List<String> values) {
            addCriterion("currency_code not in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeBetween(String value1, String value2) {
            addCriterion("currency_code between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("currency_code not between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIsNull() {
            addCriterion("auth_code is null");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIsNotNull() {
            addCriterion("auth_code is not null");
            return (Criteria) this;
        }

        public Criteria andAuthCodeEqualTo(String value) {
            addCriterion("auth_code =", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotEqualTo(String value) {
            addCriterion("auth_code <>", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeGreaterThan(String value) {
            addCriterion("auth_code >", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeGreaterThanOrEqualTo(String value) {
            addCriterion("auth_code >=", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLessThan(String value) {
            addCriterion("auth_code <", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLessThanOrEqualTo(String value) {
            addCriterion("auth_code <=", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLike(String value) {
            addCriterion("auth_code like", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotLike(String value) {
            addCriterion("auth_code not like", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIn(List<String> values) {
            addCriterion("auth_code in", values, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotIn(List<String> values) {
            addCriterion("auth_code not in", values, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeBetween(String value1, String value2) {
            addCriterion("auth_code between", value1, value2, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotBetween(String value1, String value2) {
            addCriterion("auth_code not between", value1, value2, "authCode");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(String value) {
            addCriterion("pay_type =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(String value) {
            addCriterion("pay_type <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(String value) {
            addCriterion("pay_type >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pay_type >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(String value) {
            addCriterion("pay_type <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(String value) {
            addCriterion("pay_type <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLike(String value) {
            addCriterion("pay_type like", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotLike(String value) {
            addCriterion("pay_type not like", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<String> values) {
            addCriterion("pay_type in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<String> values) {
            addCriterion("pay_type not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(String value1, String value2) {
            addCriterion("pay_type between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(String value1, String value2) {
            addCriterion("pay_type not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andIsAssuredIsNull() {
            addCriterion("is_assured is null");
            return (Criteria) this;
        }

        public Criteria andIsAssuredIsNotNull() {
            addCriterion("is_assured is not null");
            return (Criteria) this;
        }

        public Criteria andIsAssuredEqualTo(Integer value) {
            addCriterion("is_assured =", value, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredNotEqualTo(Integer value) {
            addCriterion("is_assured <>", value, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredGreaterThan(Integer value) {
            addCriterion("is_assured >", value, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_assured >=", value, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredLessThan(Integer value) {
            addCriterion("is_assured <", value, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredLessThanOrEqualTo(Integer value) {
            addCriterion("is_assured <=", value, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredIn(List<Integer> values) {
            addCriterion("is_assured in", values, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredNotIn(List<Integer> values) {
            addCriterion("is_assured not in", values, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredBetween(Integer value1, Integer value2) {
            addCriterion("is_assured between", value1, value2, "isAssured");
            return (Criteria) this;
        }

        public Criteria andIsAssuredNotBetween(Integer value1, Integer value2) {
            addCriterion("is_assured not between", value1, value2, "isAssured");
            return (Criteria) this;
        }

        public Criteria andBgUrlIsNull() {
            addCriterion("bg_url is null");
            return (Criteria) this;
        }

        public Criteria andBgUrlIsNotNull() {
            addCriterion("bg_url is not null");
            return (Criteria) this;
        }

        public Criteria andBgUrlEqualTo(String value) {
            addCriterion("bg_url =", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotEqualTo(String value) {
            addCriterion("bg_url <>", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlGreaterThan(String value) {
            addCriterion("bg_url >", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("bg_url >=", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlLessThan(String value) {
            addCriterion("bg_url <", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlLessThanOrEqualTo(String value) {
            addCriterion("bg_url <=", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlLike(String value) {
            addCriterion("bg_url like", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotLike(String value) {
            addCriterion("bg_url not like", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlIn(List<String> values) {
            addCriterion("bg_url in", values, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotIn(List<String> values) {
            addCriterion("bg_url not in", values, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlBetween(String value1, String value2) {
            addCriterion("bg_url between", value1, value2, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotBetween(String value1, String value2) {
            addCriterion("bg_url not between", value1, value2, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andStlDateIsNull() {
            addCriterion("stl_date is null");
            return (Criteria) this;
        }

        public Criteria andStlDateIsNotNull() {
            addCriterion("stl_date is not null");
            return (Criteria) this;
        }

        public Criteria andStlDateEqualTo(Date value) {
            addCriterion("stl_date =", value, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateNotEqualTo(Date value) {
            addCriterion("stl_date <>", value, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateGreaterThan(Date value) {
            addCriterion("stl_date >", value, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateGreaterThanOrEqualTo(Date value) {
            addCriterion("stl_date >=", value, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateLessThan(Date value) {
            addCriterion("stl_date <", value, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateLessThanOrEqualTo(Date value) {
            addCriterion("stl_date <=", value, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateIn(List<Date> values) {
            addCriterion("stl_date in", values, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateNotIn(List<Date> values) {
            addCriterion("stl_date not in", values, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateBetween(Date value1, Date value2) {
            addCriterion("stl_date between", value1, value2, "stlDate");
            return (Criteria) this;
        }

        public Criteria andStlDateNotBetween(Date value1, Date value2) {
            addCriterion("stl_date not between", value1, value2, "stlDate");
            return (Criteria) this;
        }

        public Criteria andPayUrlIsNull() {
            addCriterion("pay_url is null");
            return (Criteria) this;
        }

        public Criteria andPayUrlIsNotNull() {
            addCriterion("pay_url is not null");
            return (Criteria) this;
        }

        public Criteria andPayUrlEqualTo(String value) {
            addCriterion("pay_url =", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlNotEqualTo(String value) {
            addCriterion("pay_url <>", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlGreaterThan(String value) {
            addCriterion("pay_url >", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pay_url >=", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlLessThan(String value) {
            addCriterion("pay_url <", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlLessThanOrEqualTo(String value) {
            addCriterion("pay_url <=", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlLike(String value) {
            addCriterion("pay_url like", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlNotLike(String value) {
            addCriterion("pay_url not like", value, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlIn(List<String> values) {
            addCriterion("pay_url in", values, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlNotIn(List<String> values) {
            addCriterion("pay_url not in", values, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlBetween(String value1, String value2) {
            addCriterion("pay_url between", value1, value2, "payUrl");
            return (Criteria) this;
        }

        public Criteria andPayUrlNotBetween(String value1, String value2) {
            addCriterion("pay_url not between", value1, value2, "payUrl");
            return (Criteria) this;
        }

        public Criteria andSecureTypeIsNull() {
            addCriterion("secure_type is null");
            return (Criteria) this;
        }

        public Criteria andSecureTypeIsNotNull() {
            addCriterion("secure_type is not null");
            return (Criteria) this;
        }

        public Criteria andSecureTypeEqualTo(Integer value) {
            addCriterion("secure_type =", value, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeNotEqualTo(Integer value) {
            addCriterion("secure_type <>", value, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeGreaterThan(Integer value) {
            addCriterion("secure_type >", value, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("secure_type >=", value, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeLessThan(Integer value) {
            addCriterion("secure_type <", value, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeLessThanOrEqualTo(Integer value) {
            addCriterion("secure_type <=", value, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeIn(List<Integer> values) {
            addCriterion("secure_type in", values, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeNotIn(List<Integer> values) {
            addCriterion("secure_type not in", values, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeBetween(Integer value1, Integer value2) {
            addCriterion("secure_type between", value1, value2, "secureType");
            return (Criteria) this;
        }

        public Criteria andSecureTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("secure_type not between", value1, value2, "secureType");
            return (Criteria) this;
        }

        public Criteria andRespCodeIsNull() {
            addCriterion("resp_code is null");
            return (Criteria) this;
        }

        public Criteria andRespCodeIsNotNull() {
            addCriterion("resp_code is not null");
            return (Criteria) this;
        }

        public Criteria andRespCodeEqualTo(String value) {
            addCriterion("resp_code =", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotEqualTo(String value) {
            addCriterion("resp_code <>", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeGreaterThan(String value) {
            addCriterion("resp_code >", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeGreaterThanOrEqualTo(String value) {
            addCriterion("resp_code >=", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeLessThan(String value) {
            addCriterion("resp_code <", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeLessThanOrEqualTo(String value) {
            addCriterion("resp_code <=", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeLike(String value) {
            addCriterion("resp_code like", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotLike(String value) {
            addCriterion("resp_code not like", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeIn(List<String> values) {
            addCriterion("resp_code in", values, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotIn(List<String> values) {
            addCriterion("resp_code not in", values, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeBetween(String value1, String value2) {
            addCriterion("resp_code between", value1, value2, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotBetween(String value1, String value2) {
            addCriterion("resp_code not between", value1, value2, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespMsgIsNull() {
            addCriterion("resp_msg is null");
            return (Criteria) this;
        }

        public Criteria andRespMsgIsNotNull() {
            addCriterion("resp_msg is not null");
            return (Criteria) this;
        }

        public Criteria andRespMsgEqualTo(String value) {
            addCriterion("resp_msg =", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgNotEqualTo(String value) {
            addCriterion("resp_msg <>", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgGreaterThan(String value) {
            addCriterion("resp_msg >", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgGreaterThanOrEqualTo(String value) {
            addCriterion("resp_msg >=", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgLessThan(String value) {
            addCriterion("resp_msg <", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgLessThanOrEqualTo(String value) {
            addCriterion("resp_msg <=", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgLike(String value) {
            addCriterion("resp_msg like", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgNotLike(String value) {
            addCriterion("resp_msg not like", value, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgIn(List<String> values) {
            addCriterion("resp_msg in", values, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgNotIn(List<String> values) {
            addCriterion("resp_msg not in", values, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgBetween(String value1, String value2) {
            addCriterion("resp_msg between", value1, value2, "respMsg");
            return (Criteria) this;
        }

        public Criteria andRespMsgNotBetween(String value1, String value2) {
            addCriterion("resp_msg not between", value1, value2, "respMsg");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andDataMapIsNull() {
            addCriterion("data_map is null");
            return (Criteria) this;
        }

        public Criteria andDataMapIsNotNull() {
            addCriterion("data_map is not null");
            return (Criteria) this;
        }

        public Criteria andDataMapEqualTo(String value) {
            addCriterion("data_map =", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotEqualTo(String value) {
            addCriterion("data_map <>", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapGreaterThan(String value) {
            addCriterion("data_map >", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapGreaterThanOrEqualTo(String value) {
            addCriterion("data_map >=", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapLessThan(String value) {
            addCriterion("data_map <", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapLessThanOrEqualTo(String value) {
            addCriterion("data_map <=", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapLike(String value) {
            addCriterion("data_map like", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotLike(String value) {
            addCriterion("data_map not like", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapIn(List<String> values) {
            addCriterion("data_map in", values, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotIn(List<String> values) {
            addCriterion("data_map not in", values, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapBetween(String value1, String value2) {
            addCriterion("data_map between", value1, value2, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotBetween(String value1, String value2) {
            addCriterion("data_map not between", value1, value2, "dataMap");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}