package com.bill99.mam.platform.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public OrderDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(Long value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(Long value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(Long value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(Long value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<Long> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<Long> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(Long value1, Long value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIsNull() {
            addCriterion("sub_merchant_uid is null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIsNotNull() {
            addCriterion("sub_merchant_uid is not null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidEqualTo(Long value) {
            addCriterion("sub_merchant_uid =", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotEqualTo(Long value) {
            addCriterion("sub_merchant_uid <>", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidGreaterThan(Long value) {
            addCriterion("sub_merchant_uid >", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidGreaterThanOrEqualTo(Long value) {
            addCriterion("sub_merchant_uid >=", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidLessThan(Long value) {
            addCriterion("sub_merchant_uid <", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidLessThanOrEqualTo(Long value) {
            addCriterion("sub_merchant_uid <=", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIn(List<Long> values) {
            addCriterion("sub_merchant_uid in", values, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotIn(List<Long> values) {
            addCriterion("sub_merchant_uid not in", values, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidBetween(Long value1, Long value2) {
            addCriterion("sub_merchant_uid between", value1, value2, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotBetween(Long value1, Long value2) {
            addCriterion("sub_merchant_uid not between", value1, value2, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameIsNull() {
            addCriterion("sub_merchant_name is null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameIsNotNull() {
            addCriterion("sub_merchant_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameEqualTo(String value) {
            addCriterion("sub_merchant_name =", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameNotEqualTo(String value) {
            addCriterion("sub_merchant_name <>", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameGreaterThan(String value) {
            addCriterion("sub_merchant_name >", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameGreaterThanOrEqualTo(String value) {
            addCriterion("sub_merchant_name >=", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameLessThan(String value) {
            addCriterion("sub_merchant_name <", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameLessThanOrEqualTo(String value) {
            addCriterion("sub_merchant_name <=", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameLike(String value) {
            addCriterion("sub_merchant_name like", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameNotLike(String value) {
            addCriterion("sub_merchant_name not like", value, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameIn(List<String> values) {
            addCriterion("sub_merchant_name in", values, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameNotIn(List<String> values) {
            addCriterion("sub_merchant_name not in", values, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameBetween(String value1, String value2) {
            addCriterion("sub_merchant_name between", value1, value2, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andSubMerchantNameNotBetween(String value1, String value2) {
            addCriterion("sub_merchant_name not between", value1, value2, "subMerchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformIsNull() {
            addCriterion("merchant_is_platform is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformIsNotNull() {
            addCriterion("merchant_is_platform is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformEqualTo(Integer value) {
            addCriterion("merchant_is_platform =", value, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformNotEqualTo(Integer value) {
            addCriterion("merchant_is_platform <>", value, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformGreaterThan(Integer value) {
            addCriterion("merchant_is_platform >", value, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformGreaterThanOrEqualTo(Integer value) {
            addCriterion("merchant_is_platform >=", value, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformLessThan(Integer value) {
            addCriterion("merchant_is_platform <", value, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformLessThanOrEqualTo(Integer value) {
            addCriterion("merchant_is_platform <=", value, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformIn(List<Integer> values) {
            addCriterion("merchant_is_platform in", values, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformNotIn(List<Integer> values) {
            addCriterion("merchant_is_platform not in", values, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformBetween(Integer value1, Integer value2) {
            addCriterion("merchant_is_platform between", value1, value2, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andMerchantIsPlatformNotBetween(Integer value1, Integer value2) {
            addCriterion("merchant_is_platform not between", value1, value2, "merchantIsPlatform");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNull() {
            addCriterion("order_amount is null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNotNull() {
            addCriterion("order_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountEqualTo(Long value) {
            addCriterion("order_amount =", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotEqualTo(Long value) {
            addCriterion("order_amount <>", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThan(Long value) {
            addCriterion("order_amount >", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("order_amount >=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThan(Long value) {
            addCriterion("order_amount <", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThanOrEqualTo(Long value) {
            addCriterion("order_amount <=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIn(List<Long> values) {
            addCriterion("order_amount in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotIn(List<Long> values) {
            addCriterion("order_amount not in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountBetween(Long value1, Long value2) {
            addCriterion("order_amount between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotBetween(Long value1, Long value2) {
            addCriterion("order_amount not between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountIsNull() {
            addCriterion("merchant_ledger_amount is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountIsNotNull() {
            addCriterion("merchant_ledger_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountEqualTo(Long value) {
            addCriterion("merchant_ledger_amount =", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountNotEqualTo(Long value) {
            addCriterion("merchant_ledger_amount <>", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountGreaterThan(Long value) {
            addCriterion("merchant_ledger_amount >", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("merchant_ledger_amount >=", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountLessThan(Long value) {
            addCriterion("merchant_ledger_amount <", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountLessThanOrEqualTo(Long value) {
            addCriterion("merchant_ledger_amount <=", value, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountIn(List<Long> values) {
            addCriterion("merchant_ledger_amount in", values, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountNotIn(List<Long> values) {
            addCriterion("merchant_ledger_amount not in", values, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountBetween(Long value1, Long value2) {
            addCriterion("merchant_ledger_amount between", value1, value2, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andMerchantLedgerAmountNotBetween(Long value1, Long value2) {
            addCriterion("merchant_ledger_amount not between", value1, value2, "merchantLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountIsNull() {
            addCriterion("platform_ledger_amount is null");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountIsNotNull() {
            addCriterion("platform_ledger_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountEqualTo(Long value) {
            addCriterion("platform_ledger_amount =", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountNotEqualTo(Long value) {
            addCriterion("platform_ledger_amount <>", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountGreaterThan(Long value) {
            addCriterion("platform_ledger_amount >", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("platform_ledger_amount >=", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountLessThan(Long value) {
            addCriterion("platform_ledger_amount <", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountLessThanOrEqualTo(Long value) {
            addCriterion("platform_ledger_amount <=", value, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountIn(List<Long> values) {
            addCriterion("platform_ledger_amount in", values, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountNotIn(List<Long> values) {
            addCriterion("platform_ledger_amount not in", values, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountBetween(Long value1, Long value2) {
            addCriterion("platform_ledger_amount between", value1, value2, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformLedgerAmountNotBetween(Long value1, Long value2) {
            addCriterion("platform_ledger_amount not between", value1, value2, "platformLedgerAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNull() {
            addCriterion("refund_amount is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNotNull() {
            addCriterion("refund_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountEqualTo(Long value) {
            addCriterion("refund_amount =", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotEqualTo(Long value) {
            addCriterion("refund_amount <>", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThan(Long value) {
            addCriterion("refund_amount >", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("refund_amount >=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThan(Long value) {
            addCriterion("refund_amount <", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThanOrEqualTo(Long value) {
            addCriterion("refund_amount <=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIn(List<Long> values) {
            addCriterion("refund_amount in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotIn(List<Long> values) {
            addCriterion("refund_amount not in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountBetween(Long value1, Long value2) {
            addCriterion("refund_amount between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotBetween(Long value1, Long value2) {
            addCriterion("refund_amount not between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountIsNull() {
            addCriterion("setttle_amount is null");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountIsNotNull() {
            addCriterion("setttle_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountEqualTo(Long value) {
            addCriterion("setttle_amount =", value, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountNotEqualTo(Long value) {
            addCriterion("setttle_amount <>", value, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountGreaterThan(Long value) {
            addCriterion("setttle_amount >", value, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("setttle_amount >=", value, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountLessThan(Long value) {
            addCriterion("setttle_amount <", value, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountLessThanOrEqualTo(Long value) {
            addCriterion("setttle_amount <=", value, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountIn(List<Long> values) {
            addCriterion("setttle_amount in", values, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountNotIn(List<Long> values) {
            addCriterion("setttle_amount not in", values, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountBetween(Long value1, Long value2) {
            addCriterion("setttle_amount between", value1, value2, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andSetttleAmountNotBetween(Long value1, Long value2) {
            addCriterion("setttle_amount not between", value1, value2, "setttleAmount");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(Long value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(Long value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(Long value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(Long value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(Long value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(Long value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<Long> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<Long> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(Long value1, Long value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(Long value1, Long value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("pay_status is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(Integer value) {
            addCriterion("pay_status =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(Integer value) {
            addCriterion("pay_status <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(Integer value) {
            addCriterion("pay_status >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_status >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(Integer value) {
            addCriterion("pay_status <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("pay_status <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<Integer> values) {
            addCriterion("pay_status in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<Integer> values) {
            addCriterion("pay_status not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(Integer value1, Integer value2) {
            addCriterion("pay_status between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_status not between", value1, value2, "payStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_order_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}