package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class OrderProductItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.order_detail_no
     *
     * @mbg.generated
     */
    private Long orderDetailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.product_tag
     *
     * @mbg.generated
     */
    private Long productTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.product_num
     *
     * @mbg.generated
     */
    private Long productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.product_price
     *
     * @mbg.generated
     */
    private Long productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.ledger_rate
     *
     * @mbg.generated
     */
    private Integer ledgerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.merchant_ledger_amount
     *
     * @mbg.generated
     */
    private Long merchantLedgerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.platform_ledger_amount
     *
     * @mbg.generated
     */
    private Long platformLedgerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.product_category
     *
     * @mbg.generated
     */
    private String productCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_productitem.pay_status
     *
     * @mbg.generated
     */
    private Integer payStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.id
     *
     * @return the value of t_mock_order_productitem.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.id
     *
     * @param id the value for t_mock_order_productitem.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.order_detail_no
     *
     * @return the value of t_mock_order_productitem.order_detail_no
     *
     * @mbg.generated
     */
    public Long getOrderDetailNo() {
        return orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.order_detail_no
     *
     * @param orderDetailNo the value for t_mock_order_productitem.order_detail_no
     *
     * @mbg.generated
     */
    public void setOrderDetailNo(Long orderDetailNo) {
        this.orderDetailNo = orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.product_tag
     *
     * @return the value of t_mock_order_productitem.product_tag
     *
     * @mbg.generated
     */
    public Long getProductTag() {
        return productTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.product_tag
     *
     * @param productTag the value for t_mock_order_productitem.product_tag
     *
     * @mbg.generated
     */
    public void setProductTag(Long productTag) {
        this.productTag = productTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.product_name
     *
     * @return the value of t_mock_order_productitem.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.product_name
     *
     * @param productName the value for t_mock_order_productitem.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.product_num
     *
     * @return the value of t_mock_order_productitem.product_num
     *
     * @mbg.generated
     */
    public Long getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.product_num
     *
     * @param productNum the value for t_mock_order_productitem.product_num
     *
     * @mbg.generated
     */
    public void setProductNum(Long productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.product_price
     *
     * @return the value of t_mock_order_productitem.product_price
     *
     * @mbg.generated
     */
    public Long getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.product_price
     *
     * @param productPrice the value for t_mock_order_productitem.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(Long productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.ledger_rate
     *
     * @return the value of t_mock_order_productitem.ledger_rate
     *
     * @mbg.generated
     */
    public Integer getLedgerRate() {
        return ledgerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.ledger_rate
     *
     * @param ledgerRate the value for t_mock_order_productitem.ledger_rate
     *
     * @mbg.generated
     */
    public void setLedgerRate(Integer ledgerRate) {
        this.ledgerRate = ledgerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.merchant_ledger_amount
     *
     * @return the value of t_mock_order_productitem.merchant_ledger_amount
     *
     * @mbg.generated
     */
    public Long getMerchantLedgerAmount() {
        return merchantLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.merchant_ledger_amount
     *
     * @param merchantLedgerAmount the value for t_mock_order_productitem.merchant_ledger_amount
     *
     * @mbg.generated
     */
    public void setMerchantLedgerAmount(Long merchantLedgerAmount) {
        this.merchantLedgerAmount = merchantLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.platform_ledger_amount
     *
     * @return the value of t_mock_order_productitem.platform_ledger_amount
     *
     * @mbg.generated
     */
    public Long getPlatformLedgerAmount() {
        return platformLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.platform_ledger_amount
     *
     * @param platformLedgerAmount the value for t_mock_order_productitem.platform_ledger_amount
     *
     * @mbg.generated
     */
    public void setPlatformLedgerAmount(Long platformLedgerAmount) {
        this.platformLedgerAmount = platformLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.product_category
     *
     * @return the value of t_mock_order_productitem.product_category
     *
     * @mbg.generated
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.product_category
     *
     * @param productCategory the value for t_mock_order_productitem.product_category
     *
     * @mbg.generated
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory == null ? null : productCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.product_desc
     *
     * @return the value of t_mock_order_productitem.product_desc
     *
     * @mbg.generated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.product_desc
     *
     * @param productDesc the value for t_mock_order_productitem.product_desc
     *
     * @mbg.generated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.update_time
     *
     * @return the value of t_mock_order_productitem.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.update_time
     *
     * @param updateTime the value for t_mock_order_productitem.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.create_time
     *
     * @return the value of t_mock_order_productitem.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.create_time
     *
     * @param createTime the value for t_mock_order_productitem.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.order_status
     *
     * @return the value of t_mock_order_productitem.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.order_status
     *
     * @param orderStatus the value for t_mock_order_productitem.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_productitem.pay_status
     *
     * @return the value of t_mock_order_productitem.pay_status
     *
     * @mbg.generated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_productitem.pay_status
     *
     * @param payStatus the value for t_mock_order_productitem.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }
}