package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.order_no
     *
     * @mbg.generated
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.sub_merchant_uid
     *
     * @mbg.generated
     */
    private Long subMerchantUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.sub_merchant_name
     *
     * @mbg.generated
     */
    private String subMerchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.merchant_is_platform
     *
     * @mbg.generated
     */
    private Integer merchantIsPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.order_amount
     *
     * @mbg.generated
     */
    private Long orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.merchant_ledger_amount
     *
     * @mbg.generated
     */
    private Long merchantLedgerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.platform_ledger_amount
     *
     * @mbg.generated
     */
    private Long platformLedgerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.refund_amount
     *
     * @mbg.generated
     */
    private Long refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.setttle_amount
     *
     * @mbg.generated
     */
    private Long setttleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.order_type
     *
     * @mbg.generated
     */
    private Long orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_order_detail.pay_status
     *
     * @mbg.generated
     */
    private Integer payStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.id
     *
     * @return the value of t_mock_order_detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.id
     *
     * @param id the value for t_mock_order_detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.order_no
     *
     * @return the value of t_mock_order_detail.order_no
     *
     * @mbg.generated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.order_no
     *
     * @param orderNo the value for t_mock_order_detail.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.sub_merchant_uid
     *
     * @return the value of t_mock_order_detail.sub_merchant_uid
     *
     * @mbg.generated
     */
    public Long getSubMerchantUid() {
        return subMerchantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.sub_merchant_uid
     *
     * @param subMerchantUid the value for t_mock_order_detail.sub_merchant_uid
     *
     * @mbg.generated
     */
    public void setSubMerchantUid(Long subMerchantUid) {
        this.subMerchantUid = subMerchantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.sub_merchant_name
     *
     * @return the value of t_mock_order_detail.sub_merchant_name
     *
     * @mbg.generated
     */
    public String getSubMerchantName() {
        return subMerchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.sub_merchant_name
     *
     * @param subMerchantName the value for t_mock_order_detail.sub_merchant_name
     *
     * @mbg.generated
     */
    public void setSubMerchantName(String subMerchantName) {
        this.subMerchantName = subMerchantName == null ? null : subMerchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.merchant_is_platform
     *
     * @return the value of t_mock_order_detail.merchant_is_platform
     *
     * @mbg.generated
     */
    public Integer getMerchantIsPlatform() {
        return merchantIsPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.merchant_is_platform
     *
     * @param merchantIsPlatform the value for t_mock_order_detail.merchant_is_platform
     *
     * @mbg.generated
     */
    public void setMerchantIsPlatform(Integer merchantIsPlatform) {
        this.merchantIsPlatform = merchantIsPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.order_amount
     *
     * @return the value of t_mock_order_detail.order_amount
     *
     * @mbg.generated
     */
    public Long getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.order_amount
     *
     * @param orderAmount the value for t_mock_order_detail.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.merchant_ledger_amount
     *
     * @return the value of t_mock_order_detail.merchant_ledger_amount
     *
     * @mbg.generated
     */
    public Long getMerchantLedgerAmount() {
        return merchantLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.merchant_ledger_amount
     *
     * @param merchantLedgerAmount the value for t_mock_order_detail.merchant_ledger_amount
     *
     * @mbg.generated
     */
    public void setMerchantLedgerAmount(Long merchantLedgerAmount) {
        this.merchantLedgerAmount = merchantLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.platform_ledger_amount
     *
     * @return the value of t_mock_order_detail.platform_ledger_amount
     *
     * @mbg.generated
     */
    public Long getPlatformLedgerAmount() {
        return platformLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.platform_ledger_amount
     *
     * @param platformLedgerAmount the value for t_mock_order_detail.platform_ledger_amount
     *
     * @mbg.generated
     */
    public void setPlatformLedgerAmount(Long platformLedgerAmount) {
        this.platformLedgerAmount = platformLedgerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.refund_amount
     *
     * @return the value of t_mock_order_detail.refund_amount
     *
     * @mbg.generated
     */
    public Long getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.refund_amount
     *
     * @param refundAmount the value for t_mock_order_detail.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(Long refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.setttle_amount
     *
     * @return the value of t_mock_order_detail.setttle_amount
     *
     * @mbg.generated
     */
    public Long getSetttleAmount() {
        return setttleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.setttle_amount
     *
     * @param setttleAmount the value for t_mock_order_detail.setttle_amount
     *
     * @mbg.generated
     */
    public void setSetttleAmount(Long setttleAmount) {
        this.setttleAmount = setttleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.order_type
     *
     * @return the value of t_mock_order_detail.order_type
     *
     * @mbg.generated
     */
    public Long getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.order_type
     *
     * @param orderType the value for t_mock_order_detail.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Long orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.update_time
     *
     * @return the value of t_mock_order_detail.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.update_time
     *
     * @param updateTime the value for t_mock_order_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.create_time
     *
     * @return the value of t_mock_order_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.create_time
     *
     * @param createTime the value for t_mock_order_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.order_status
     *
     * @return the value of t_mock_order_detail.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.order_status
     *
     * @param orderStatus the value for t_mock_order_detail.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_order_detail.pay_status
     *
     * @return the value of t_mock_order_detail.pay_status
     *
     * @mbg.generated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_order_detail.pay_status
     *
     * @param payStatus the value for t_mock_order_detail.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }
}