package com.bill99.mam.platform.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RefundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public RefundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRefundNoIsNull() {
            addCriterion("refund_No is null");
            return (Criteria) this;
        }

        public Criteria andRefundNoIsNotNull() {
            addCriterion("refund_No is not null");
            return (Criteria) this;
        }

        public Criteria andRefundNoEqualTo(Long value) {
            addCriterion("refund_No =", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoNotEqualTo(Long value) {
            addCriterion("refund_No <>", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoGreaterThan(Long value) {
            addCriterion("refund_No >", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoGreaterThanOrEqualTo(Long value) {
            addCriterion("refund_No >=", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoLessThan(Long value) {
            addCriterion("refund_No <", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoLessThanOrEqualTo(Long value) {
            addCriterion("refund_No <=", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoIn(List<Long> values) {
            addCriterion("refund_No in", values, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoNotIn(List<Long> values) {
            addCriterion("refund_No not in", values, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoBetween(Long value1, Long value2) {
            addCriterion("refund_No between", value1, value2, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoNotBetween(Long value1, Long value2) {
            addCriterion("refund_No not between", value1, value2, "refundNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoIsNull() {
            addCriterion("orig_order_No is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoIsNotNull() {
            addCriterion("orig_order_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoEqualTo(Long value) {
            addCriterion("orig_order_No =", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoNotEqualTo(Long value) {
            addCriterion("orig_order_No <>", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoGreaterThan(Long value) {
            addCriterion("orig_order_No >", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("orig_order_No >=", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoLessThan(Long value) {
            addCriterion("orig_order_No <", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("orig_order_No <=", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoIn(List<Long> values) {
            addCriterion("orig_order_No in", values, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoNotIn(List<Long> values) {
            addCriterion("orig_order_No not in", values, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoBetween(Long value1, Long value2) {
            addCriterion("orig_order_No between", value1, value2, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("orig_order_No not between", value1, value2, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIsNull() {
            addCriterion("SUB_MERCHANT_UID is null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIsNotNull() {
            addCriterion("SUB_MERCHANT_UID is not null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID =", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID <>", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidGreaterThan(Long value) {
            addCriterion("SUB_MERCHANT_UID >", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidGreaterThanOrEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID >=", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidLessThan(Long value) {
            addCriterion("SUB_MERCHANT_UID <", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidLessThanOrEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID <=", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIn(List<Long> values) {
            addCriterion("SUB_MERCHANT_UID in", values, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotIn(List<Long> values) {
            addCriterion("SUB_MERCHANT_UID not in", values, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidBetween(Long value1, Long value2) {
            addCriterion("SUB_MERCHANT_UID between", value1, value2, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotBetween(Long value1, Long value2) {
            addCriterion("SUB_MERCHANT_UID not between", value1, value2, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSharingDataIsNull() {
            addCriterion("sharing_Data is null");
            return (Criteria) this;
        }

        public Criteria andSharingDataIsNotNull() {
            addCriterion("sharing_Data is not null");
            return (Criteria) this;
        }

        public Criteria andSharingDataEqualTo(String value) {
            addCriterion("sharing_Data =", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotEqualTo(String value) {
            addCriterion("sharing_Data <>", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataGreaterThan(String value) {
            addCriterion("sharing_Data >", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataGreaterThanOrEqualTo(String value) {
            addCriterion("sharing_Data >=", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataLessThan(String value) {
            addCriterion("sharing_Data <", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataLessThanOrEqualTo(String value) {
            addCriterion("sharing_Data <=", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataLike(String value) {
            addCriterion("sharing_Data like", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotLike(String value) {
            addCriterion("sharing_Data not like", value, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataIn(List<String> values) {
            addCriterion("sharing_Data in", values, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotIn(List<String> values) {
            addCriterion("sharing_Data not in", values, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataBetween(String value1, String value2) {
            addCriterion("sharing_Data between", value1, value2, "sharingData");
            return (Criteria) this;
        }

        public Criteria andSharingDataNotBetween(String value1, String value2) {
            addCriterion("sharing_Data not between", value1, value2, "sharingData");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNull() {
            addCriterion("REFUND_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNotNull() {
            addCriterion("REFUND_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountEqualTo(Long value) {
            addCriterion("REFUND_AMOUNT =", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotEqualTo(Long value) {
            addCriterion("REFUND_AMOUNT <>", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThan(Long value) {
            addCriterion("REFUND_AMOUNT >", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("REFUND_AMOUNT >=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThan(Long value) {
            addCriterion("REFUND_AMOUNT <", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThanOrEqualTo(Long value) {
            addCriterion("REFUND_AMOUNT <=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIn(List<Long> values) {
            addCriterion("REFUND_AMOUNT in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotIn(List<Long> values) {
            addCriterion("REFUND_AMOUNT not in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountBetween(Long value1, Long value2) {
            addCriterion("REFUND_AMOUNT between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotBetween(Long value1, Long value2) {
            addCriterion("REFUND_AMOUNT not between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIsNull() {
            addCriterion("REFUND_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIsNotNull() {
            addCriterion("REFUND_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRefundStatusEqualTo(Integer value) {
            addCriterion("REFUND_STATUS =", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotEqualTo(Integer value) {
            addCriterion("REFUND_STATUS <>", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusGreaterThan(Integer value) {
            addCriterion("REFUND_STATUS >", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("REFUND_STATUS >=", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLessThan(Integer value) {
            addCriterion("REFUND_STATUS <", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLessThanOrEqualTo(Integer value) {
            addCriterion("REFUND_STATUS <=", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIn(List<Integer> values) {
            addCriterion("REFUND_STATUS in", values, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotIn(List<Integer> values) {
            addCriterion("REFUND_STATUS not in", values, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusBetween(Integer value1, Integer value2) {
            addCriterion("REFUND_STATUS between", value1, value2, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("REFUND_STATUS not between", value1, value2, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIsNull() {
            addCriterion("payee_UId is null");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIsNotNull() {
            addCriterion("payee_UId is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeUidEqualTo(Long value) {
            addCriterion("payee_UId =", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotEqualTo(Long value) {
            addCriterion("payee_UId <>", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidGreaterThan(Long value) {
            addCriterion("payee_UId >", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidGreaterThanOrEqualTo(Long value) {
            addCriterion("payee_UId >=", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLessThan(Long value) {
            addCriterion("payee_UId <", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLessThanOrEqualTo(Long value) {
            addCriterion("payee_UId <=", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIn(List<Long> values) {
            addCriterion("payee_UId in", values, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotIn(List<Long> values) {
            addCriterion("payee_UId not in", values, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidBetween(Long value1, Long value2) {
            addCriterion("payee_UId between", value1, value2, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotBetween(Long value1, Long value2) {
            addCriterion("payee_UId not between", value1, value2, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoIsNull() {
            addCriterion("bill_Order_No is null");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoIsNotNull() {
            addCriterion("bill_Order_No is not null");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoEqualTo(String value) {
            addCriterion("bill_Order_No =", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotEqualTo(String value) {
            addCriterion("bill_Order_No <>", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoGreaterThan(String value) {
            addCriterion("bill_Order_No >", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("bill_Order_No >=", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoLessThan(String value) {
            addCriterion("bill_Order_No <", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoLessThanOrEqualTo(String value) {
            addCriterion("bill_Order_No <=", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoLike(String value) {
            addCriterion("bill_Order_No like", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotLike(String value) {
            addCriterion("bill_Order_No not like", value, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoIn(List<String> values) {
            addCriterion("bill_Order_No in", values, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotIn(List<String> values) {
            addCriterion("bill_Order_No not in", values, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoBetween(String value1, String value2) {
            addCriterion("bill_Order_No between", value1, value2, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andBillOrderNoNotBetween(String value1, String value2) {
            addCriterion("bill_Order_No not between", value1, value2, "billOrderNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNull() {
            addCriterion("TRADE_NO is null");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNotNull() {
            addCriterion("TRADE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNoEqualTo(String value) {
            addCriterion("TRADE_NO =", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotEqualTo(String value) {
            addCriterion("TRADE_NO <>", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThan(String value) {
            addCriterion("TRADE_NO >", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_NO >=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThan(String value) {
            addCriterion("TRADE_NO <", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThanOrEqualTo(String value) {
            addCriterion("TRADE_NO <=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLike(String value) {
            addCriterion("TRADE_NO like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotLike(String value) {
            addCriterion("TRADE_NO not like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIn(List<String> values) {
            addCriterion("TRADE_NO in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotIn(List<String> values) {
            addCriterion("TRADE_NO not in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoBetween(String value1, String value2) {
            addCriterion("TRADE_NO between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotBetween(String value1, String value2) {
            addCriterion("TRADE_NO not between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeIsNull() {
            addCriterion("REFUND_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeIsNotNull() {
            addCriterion("REFUND_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeEqualTo(Date value) {
            addCriterion("REFUND_START_TIME =", value, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeNotEqualTo(Date value) {
            addCriterion("REFUND_START_TIME <>", value, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeGreaterThan(Date value) {
            addCriterion("REFUND_START_TIME >", value, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REFUND_START_TIME >=", value, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeLessThan(Date value) {
            addCriterion("REFUND_START_TIME <", value, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("REFUND_START_TIME <=", value, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeIn(List<Date> values) {
            addCriterion("REFUND_START_TIME in", values, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeNotIn(List<Date> values) {
            addCriterion("REFUND_START_TIME not in", values, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeBetween(Date value1, Date value2) {
            addCriterion("REFUND_START_TIME between", value1, value2, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("REFUND_START_TIME not between", value1, value2, "refundStartTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeIsNull() {
            addCriterion("REFUND_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeIsNotNull() {
            addCriterion("REFUND_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeEqualTo(Date value) {
            addCriterion("REFUND_END_TIME =", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeNotEqualTo(Date value) {
            addCriterion("REFUND_END_TIME <>", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeGreaterThan(Date value) {
            addCriterion("REFUND_END_TIME >", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REFUND_END_TIME >=", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeLessThan(Date value) {
            addCriterion("REFUND_END_TIME <", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("REFUND_END_TIME <=", value, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeIn(List<Date> values) {
            addCriterion("REFUND_END_TIME in", values, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeNotIn(List<Date> values) {
            addCriterion("REFUND_END_TIME not in", values, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeBetween(Date value1, Date value2) {
            addCriterion("REFUND_END_TIME between", value1, value2, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andRefundEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("REFUND_END_TIME not between", value1, value2, "refundEndTime");
            return (Criteria) this;
        }

        public Criteria andBgUrlIsNull() {
            addCriterion("bg_Url is null");
            return (Criteria) this;
        }

        public Criteria andBgUrlIsNotNull() {
            addCriterion("bg_Url is not null");
            return (Criteria) this;
        }

        public Criteria andBgUrlEqualTo(String value) {
            addCriterion("bg_Url =", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotEqualTo(String value) {
            addCriterion("bg_Url <>", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlGreaterThan(String value) {
            addCriterion("bg_Url >", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("bg_Url >=", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlLessThan(String value) {
            addCriterion("bg_Url <", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlLessThanOrEqualTo(String value) {
            addCriterion("bg_Url <=", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlLike(String value) {
            addCriterion("bg_Url like", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotLike(String value) {
            addCriterion("bg_Url not like", value, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlIn(List<String> values) {
            addCriterion("bg_Url in", values, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotIn(List<String> values) {
            addCriterion("bg_Url not in", values, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlBetween(String value1, String value2) {
            addCriterion("bg_Url between", value1, value2, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andBgUrlNotBetween(String value1, String value2) {
            addCriterion("bg_Url not between", value1, value2, "bgUrl");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNull() {
            addCriterion("ERROR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNotNull() {
            addCriterion("ERROR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeEqualTo(String value) {
            addCriterion("ERROR_CODE =", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotEqualTo(String value) {
            addCriterion("ERROR_CODE <>", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThan(String value) {
            addCriterion("ERROR_CODE >", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_CODE >=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThan(String value) {
            addCriterion("ERROR_CODE <", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThanOrEqualTo(String value) {
            addCriterion("ERROR_CODE <=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLike(String value) {
            addCriterion("ERROR_CODE like", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotLike(String value) {
            addCriterion("ERROR_CODE not like", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIn(List<String> values) {
            addCriterion("ERROR_CODE in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotIn(List<String> values) {
            addCriterion("ERROR_CODE not in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeBetween(String value1, String value2) {
            addCriterion("ERROR_CODE between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotBetween(String value1, String value2) {
            addCriterion("ERROR_CODE not between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorInfoIsNull() {
            addCriterion("ERROR_INFO is null");
            return (Criteria) this;
        }

        public Criteria andErrorInfoIsNotNull() {
            addCriterion("ERROR_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andErrorInfoEqualTo(String value) {
            addCriterion("ERROR_INFO =", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoNotEqualTo(String value) {
            addCriterion("ERROR_INFO <>", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoGreaterThan(String value) {
            addCriterion("ERROR_INFO >", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_INFO >=", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoLessThan(String value) {
            addCriterion("ERROR_INFO <", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoLessThanOrEqualTo(String value) {
            addCriterion("ERROR_INFO <=", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoLike(String value) {
            addCriterion("ERROR_INFO like", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoNotLike(String value) {
            addCriterion("ERROR_INFO not like", value, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoIn(List<String> values) {
            addCriterion("ERROR_INFO in", values, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoNotIn(List<String> values) {
            addCriterion("ERROR_INFO not in", values, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoBetween(String value1, String value2) {
            addCriterion("ERROR_INFO between", value1, value2, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andErrorInfoNotBetween(String value1, String value2) {
            addCriterion("ERROR_INFO not between", value1, value2, "errorInfo");
            return (Criteria) this;
        }

        public Criteria andDataMapIsNull() {
            addCriterion("data_Map is null");
            return (Criteria) this;
        }

        public Criteria andDataMapIsNotNull() {
            addCriterion("data_Map is not null");
            return (Criteria) this;
        }

        public Criteria andDataMapEqualTo(String value) {
            addCriterion("data_Map =", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotEqualTo(String value) {
            addCriterion("data_Map <>", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapGreaterThan(String value) {
            addCriterion("data_Map >", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapGreaterThanOrEqualTo(String value) {
            addCriterion("data_Map >=", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapLessThan(String value) {
            addCriterion("data_Map <", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapLessThanOrEqualTo(String value) {
            addCriterion("data_Map <=", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapLike(String value) {
            addCriterion("data_Map like", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotLike(String value) {
            addCriterion("data_Map not like", value, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapIn(List<String> values) {
            addCriterion("data_Map in", values, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotIn(List<String> values) {
            addCriterion("data_Map not in", values, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapBetween(String value1, String value2) {
            addCriterion("data_Map between", value1, value2, "dataMap");
            return (Criteria) this;
        }

        public Criteria andDataMapNotBetween(String value1, String value2) {
            addCriterion("data_Map not between", value1, value2, "dataMap");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_refund
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}