package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class Refund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.refund_No
     *
     * @mbg.generated
     */
    private Long refundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.orig_order_No
     *
     * @mbg.generated
     */
    private Long origOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.SUB_MERCHANT_UID
     *
     * @mbg.generated
     */
    private Long subMerchantUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.sharing_Data
     *
     * @mbg.generated
     */
    private String sharingData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.REFUND_AMOUNT
     *
     * @mbg.generated
     */
    private Long refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.REFUND_STATUS
     *
     * @mbg.generated
     */
    private Integer refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.payee_UId
     *
     * @mbg.generated
     */
    private Long payeeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.bill_Order_No
     *
     * @mbg.generated
     */
    private String billOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.TRADE_NO
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.REFUND_START_TIME
     *
     * @mbg.generated
     */
    private Date refundStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.REFUND_END_TIME
     *
     * @mbg.generated
     */
    private Date refundEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.bg_Url
     *
     * @mbg.generated
     */
    private String bgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.ERROR_CODE
     *
     * @mbg.generated
     */
    private String errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.ERROR_INFO
     *
     * @mbg.generated
     */
    private String errorInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.data_Map
     *
     * @mbg.generated
     */
    private String dataMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_refund.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.refund_No
     *
     * @return the value of t_mock_refund.refund_No
     *
     * @mbg.generated
     */
    public Long getRefundNo() {
        return refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.refund_No
     *
     * @param refundNo the value for t_mock_refund.refund_No
     *
     * @mbg.generated
     */
    public void setRefundNo(Long refundNo) {
        this.refundNo = refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.orig_order_No
     *
     * @return the value of t_mock_refund.orig_order_No
     *
     * @mbg.generated
     */
    public Long getOrigOrderNo() {
        return origOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.orig_order_No
     *
     * @param origOrderNo the value for t_mock_refund.orig_order_No
     *
     * @mbg.generated
     */
    public void setOrigOrderNo(Long origOrderNo) {
        this.origOrderNo = origOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.SUB_MERCHANT_UID
     *
     * @return the value of t_mock_refund.SUB_MERCHANT_UID
     *
     * @mbg.generated
     */
    public Long getSubMerchantUid() {
        return subMerchantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.SUB_MERCHANT_UID
     *
     * @param subMerchantUid the value for t_mock_refund.SUB_MERCHANT_UID
     *
     * @mbg.generated
     */
    public void setSubMerchantUid(Long subMerchantUid) {
        this.subMerchantUid = subMerchantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.sharing_Data
     *
     * @return the value of t_mock_refund.sharing_Data
     *
     * @mbg.generated
     */
    public String getSharingData() {
        return sharingData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.sharing_Data
     *
     * @param sharingData the value for t_mock_refund.sharing_Data
     *
     * @mbg.generated
     */
    public void setSharingData(String sharingData) {
        this.sharingData = sharingData == null ? null : sharingData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.REFUND_AMOUNT
     *
     * @return the value of t_mock_refund.REFUND_AMOUNT
     *
     * @mbg.generated
     */
    public Long getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.REFUND_AMOUNT
     *
     * @param refundAmount the value for t_mock_refund.REFUND_AMOUNT
     *
     * @mbg.generated
     */
    public void setRefundAmount(Long refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.REFUND_STATUS
     *
     * @return the value of t_mock_refund.REFUND_STATUS
     *
     * @mbg.generated
     */
    public Integer getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.REFUND_STATUS
     *
     * @param refundStatus the value for t_mock_refund.REFUND_STATUS
     *
     * @mbg.generated
     */
    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.payee_UId
     *
     * @return the value of t_mock_refund.payee_UId
     *
     * @mbg.generated
     */
    public Long getPayeeUid() {
        return payeeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.payee_UId
     *
     * @param payeeUid the value for t_mock_refund.payee_UId
     *
     * @mbg.generated
     */
    public void setPayeeUid(Long payeeUid) {
        this.payeeUid = payeeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.bill_Order_No
     *
     * @return the value of t_mock_refund.bill_Order_No
     *
     * @mbg.generated
     */
    public String getBillOrderNo() {
        return billOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.bill_Order_No
     *
     * @param billOrderNo the value for t_mock_refund.bill_Order_No
     *
     * @mbg.generated
     */
    public void setBillOrderNo(String billOrderNo) {
        this.billOrderNo = billOrderNo == null ? null : billOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.TRADE_NO
     *
     * @return the value of t_mock_refund.TRADE_NO
     *
     * @mbg.generated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.TRADE_NO
     *
     * @param tradeNo the value for t_mock_refund.TRADE_NO
     *
     * @mbg.generated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.REFUND_START_TIME
     *
     * @return the value of t_mock_refund.REFUND_START_TIME
     *
     * @mbg.generated
     */
    public Date getRefundStartTime() {
        return refundStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.REFUND_START_TIME
     *
     * @param refundStartTime the value for t_mock_refund.REFUND_START_TIME
     *
     * @mbg.generated
     */
    public void setRefundStartTime(Date refundStartTime) {
        this.refundStartTime = refundStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.REFUND_END_TIME
     *
     * @return the value of t_mock_refund.REFUND_END_TIME
     *
     * @mbg.generated
     */
    public Date getRefundEndTime() {
        return refundEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.REFUND_END_TIME
     *
     * @param refundEndTime the value for t_mock_refund.REFUND_END_TIME
     *
     * @mbg.generated
     */
    public void setRefundEndTime(Date refundEndTime) {
        this.refundEndTime = refundEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.bg_Url
     *
     * @return the value of t_mock_refund.bg_Url
     *
     * @mbg.generated
     */
    public String getBgUrl() {
        return bgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.bg_Url
     *
     * @param bgUrl the value for t_mock_refund.bg_Url
     *
     * @mbg.generated
     */
    public void setBgUrl(String bgUrl) {
        this.bgUrl = bgUrl == null ? null : bgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.memo
     *
     * @return the value of t_mock_refund.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.memo
     *
     * @param memo the value for t_mock_refund.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.ERROR_CODE
     *
     * @return the value of t_mock_refund.ERROR_CODE
     *
     * @mbg.generated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.ERROR_CODE
     *
     * @param errorCode the value for t_mock_refund.ERROR_CODE
     *
     * @mbg.generated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.ERROR_INFO
     *
     * @return the value of t_mock_refund.ERROR_INFO
     *
     * @mbg.generated
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.ERROR_INFO
     *
     * @param errorInfo the value for t_mock_refund.ERROR_INFO
     *
     * @mbg.generated
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo == null ? null : errorInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.data_Map
     *
     * @return the value of t_mock_refund.data_Map
     *
     * @mbg.generated
     */
    public String getDataMap() {
        return dataMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.data_Map
     *
     * @param dataMap the value for t_mock_refund.data_Map
     *
     * @mbg.generated
     */
    public void setDataMap(String dataMap) {
        this.dataMap = dataMap == null ? null : dataMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.CREATE_TIME
     *
     * @return the value of t_mock_refund.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.CREATE_TIME
     *
     * @param createTime the value for t_mock_refund.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_refund.UPDATE_TIME
     *
     * @return the value of t_mock_refund.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_refund.UPDATE_TIME
     *
     * @param updateTime the value for t_mock_refund.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}