package com.bill99.mam.platform.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubRefundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public SubRefundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubRefundNoIsNull() {
            addCriterion("sub_refund_No is null");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoIsNotNull() {
            addCriterion("sub_refund_No is not null");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoEqualTo(Long value) {
            addCriterion("sub_refund_No =", value, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoNotEqualTo(Long value) {
            addCriterion("sub_refund_No <>", value, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoGreaterThan(Long value) {
            addCriterion("sub_refund_No >", value, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoGreaterThanOrEqualTo(Long value) {
            addCriterion("sub_refund_No >=", value, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoLessThan(Long value) {
            addCriterion("sub_refund_No <", value, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoLessThanOrEqualTo(Long value) {
            addCriterion("sub_refund_No <=", value, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoIn(List<Long> values) {
            addCriterion("sub_refund_No in", values, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoNotIn(List<Long> values) {
            addCriterion("sub_refund_No not in", values, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoBetween(Long value1, Long value2) {
            addCriterion("sub_refund_No between", value1, value2, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andSubRefundNoNotBetween(Long value1, Long value2) {
            addCriterion("sub_refund_No not between", value1, value2, "subRefundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoIsNull() {
            addCriterion("refund_No is null");
            return (Criteria) this;
        }

        public Criteria andRefundNoIsNotNull() {
            addCriterion("refund_No is not null");
            return (Criteria) this;
        }

        public Criteria andRefundNoEqualTo(Long value) {
            addCriterion("refund_No =", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoNotEqualTo(Long value) {
            addCriterion("refund_No <>", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoGreaterThan(Long value) {
            addCriterion("refund_No >", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoGreaterThanOrEqualTo(Long value) {
            addCriterion("refund_No >=", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoLessThan(Long value) {
            addCriterion("refund_No <", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoLessThanOrEqualTo(Long value) {
            addCriterion("refund_No <=", value, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoIn(List<Long> values) {
            addCriterion("refund_No in", values, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoNotIn(List<Long> values) {
            addCriterion("refund_No not in", values, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoBetween(Long value1, Long value2) {
            addCriterion("refund_No between", value1, value2, "refundNo");
            return (Criteria) this;
        }

        public Criteria andRefundNoNotBetween(Long value1, Long value2) {
            addCriterion("refund_No not between", value1, value2, "refundNo");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIsNull() {
            addCriterion("SUB_MERCHANT_UID is null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIsNotNull() {
            addCriterion("SUB_MERCHANT_UID is not null");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID =", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID <>", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidGreaterThan(Long value) {
            addCriterion("SUB_MERCHANT_UID >", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidGreaterThanOrEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID >=", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidLessThan(Long value) {
            addCriterion("SUB_MERCHANT_UID <", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidLessThanOrEqualTo(Long value) {
            addCriterion("SUB_MERCHANT_UID <=", value, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidIn(List<Long> values) {
            addCriterion("SUB_MERCHANT_UID in", values, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotIn(List<Long> values) {
            addCriterion("SUB_MERCHANT_UID not in", values, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidBetween(Long value1, Long value2) {
            addCriterion("SUB_MERCHANT_UID between", value1, value2, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andSubMerchantUidNotBetween(Long value1, Long value2) {
            addCriterion("SUB_MERCHANT_UID not between", value1, value2, "subMerchantUid");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoIsNull() {
            addCriterion("orig_order_No is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoIsNotNull() {
            addCriterion("orig_order_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoEqualTo(Long value) {
            addCriterion("orig_order_No =", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoNotEqualTo(Long value) {
            addCriterion("orig_order_No <>", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoGreaterThan(Long value) {
            addCriterion("orig_order_No >", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("orig_order_No >=", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoLessThan(Long value) {
            addCriterion("orig_order_No <", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("orig_order_No <=", value, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoIn(List<Long> values) {
            addCriterion("orig_order_No in", values, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoNotIn(List<Long> values) {
            addCriterion("orig_order_No not in", values, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoBetween(Long value1, Long value2) {
            addCriterion("orig_order_No between", value1, value2, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("orig_order_No not between", value1, value2, "origOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoIsNull() {
            addCriterion("orig_sub_order_No is null");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoIsNotNull() {
            addCriterion("orig_sub_order_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoEqualTo(Long value) {
            addCriterion("orig_sub_order_No =", value, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoNotEqualTo(Long value) {
            addCriterion("orig_sub_order_No <>", value, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoGreaterThan(Long value) {
            addCriterion("orig_sub_order_No >", value, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("orig_sub_order_No >=", value, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoLessThan(Long value) {
            addCriterion("orig_sub_order_No <", value, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("orig_sub_order_No <=", value, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoIn(List<Long> values) {
            addCriterion("orig_sub_order_No in", values, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoNotIn(List<Long> values) {
            addCriterion("orig_sub_order_No not in", values, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoBetween(Long value1, Long value2) {
            addCriterion("orig_sub_order_No between", value1, value2, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigSubOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("orig_sub_order_No not between", value1, value2, "origSubOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoIsNull() {
            addCriterion("orig_order_item_No is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoIsNotNull() {
            addCriterion("orig_order_item_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoEqualTo(Long value) {
            addCriterion("orig_order_item_No =", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotEqualTo(Long value) {
            addCriterion("orig_order_item_No <>", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoGreaterThan(Long value) {
            addCriterion("orig_order_item_No >", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoGreaterThanOrEqualTo(Long value) {
            addCriterion("orig_order_item_No >=", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoLessThan(Long value) {
            addCriterion("orig_order_item_No <", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoLessThanOrEqualTo(Long value) {
            addCriterion("orig_order_item_No <=", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoIn(List<Long> values) {
            addCriterion("orig_order_item_No in", values, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotIn(List<Long> values) {
            addCriterion("orig_order_item_No not in", values, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoBetween(Long value1, Long value2) {
            addCriterion("orig_order_item_No between", value1, value2, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotBetween(Long value1, Long value2) {
            addCriterion("orig_order_item_No not between", value1, value2, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mock_sub_refund
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}