package com.bill99.mam.platform.persistence.entity;

import java.util.Date;

public class SubRefund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.sub_refund_No
     *
     * @mbg.generated
     */
    private Long subRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.refund_No
     *
     * @mbg.generated
     */
    private Long refundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.SUB_MERCHANT_UID
     *
     * @mbg.generated
     */
    private Long subMerchantUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.orig_order_No
     *
     * @mbg.generated
     */
    private Long origOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.orig_sub_order_No
     *
     * @mbg.generated
     */
    private Long origSubOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.orig_order_item_No
     *
     * @mbg.generated
     */
    private Long origOrderItemNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mock_sub_refund.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.sub_refund_No
     *
     * @return the value of t_mock_sub_refund.sub_refund_No
     *
     * @mbg.generated
     */
    public Long getSubRefundNo() {
        return subRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.sub_refund_No
     *
     * @param subRefundNo the value for t_mock_sub_refund.sub_refund_No
     *
     * @mbg.generated
     */
    public void setSubRefundNo(Long subRefundNo) {
        this.subRefundNo = subRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.refund_No
     *
     * @return the value of t_mock_sub_refund.refund_No
     *
     * @mbg.generated
     */
    public Long getRefundNo() {
        return refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.refund_No
     *
     * @param refundNo the value for t_mock_sub_refund.refund_No
     *
     * @mbg.generated
     */
    public void setRefundNo(Long refundNo) {
        this.refundNo = refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.SUB_MERCHANT_UID
     *
     * @return the value of t_mock_sub_refund.SUB_MERCHANT_UID
     *
     * @mbg.generated
     */
    public Long getSubMerchantUid() {
        return subMerchantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.SUB_MERCHANT_UID
     *
     * @param subMerchantUid the value for t_mock_sub_refund.SUB_MERCHANT_UID
     *
     * @mbg.generated
     */
    public void setSubMerchantUid(Long subMerchantUid) {
        this.subMerchantUid = subMerchantUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.orig_order_No
     *
     * @return the value of t_mock_sub_refund.orig_order_No
     *
     * @mbg.generated
     */
    public Long getOrigOrderNo() {
        return origOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.orig_order_No
     *
     * @param origOrderNo the value for t_mock_sub_refund.orig_order_No
     *
     * @mbg.generated
     */
    public void setOrigOrderNo(Long origOrderNo) {
        this.origOrderNo = origOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.orig_sub_order_No
     *
     * @return the value of t_mock_sub_refund.orig_sub_order_No
     *
     * @mbg.generated
     */
    public Long getOrigSubOrderNo() {
        return origSubOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.orig_sub_order_No
     *
     * @param origSubOrderNo the value for t_mock_sub_refund.orig_sub_order_No
     *
     * @mbg.generated
     */
    public void setOrigSubOrderNo(Long origSubOrderNo) {
        this.origSubOrderNo = origSubOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.orig_order_item_No
     *
     * @return the value of t_mock_sub_refund.orig_order_item_No
     *
     * @mbg.generated
     */
    public Long getOrigOrderItemNo() {
        return origOrderItemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.orig_order_item_No
     *
     * @param origOrderItemNo the value for t_mock_sub_refund.orig_order_item_No
     *
     * @mbg.generated
     */
    public void setOrigOrderItemNo(Long origOrderItemNo) {
        this.origOrderItemNo = origOrderItemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.CREATE_TIME
     *
     * @return the value of t_mock_sub_refund.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.CREATE_TIME
     *
     * @param createTime the value for t_mock_sub_refund.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mock_sub_refund.UPDATE_TIME
     *
     * @return the value of t_mock_sub_refund.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mock_sub_refund.UPDATE_TIME
     *
     * @param updateTime the value for t_mock_sub_refund.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}