package com.bill99.mam.platform.persistence.dao;

import com.bill99.mam.platform.persistence.entity.LedgerAcctConfig;
import com.bill99.mam.platform.persistence.entity.LedgerAcctConfigExample;

import java.util.List;

public interface LedgerAcctConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    int insert(LedgerAcctConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    int insertSelective(LedgerAcctConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    List<LedgerAcctConfig> selectByExample(LedgerAcctConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    LedgerAcctConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LedgerAcctConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_ledger_acct_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LedgerAcctConfig record);
}