package com.bill99.mam.platform.persistence.dao;

import com.bill99.mam.platform.persistence.entity.LoginPassword;
import com.bill99.mam.platform.persistence.entity.LoginPasswordExample;

import java.util.List;

public interface LoginPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    int insert(LoginPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    int insertSelective(LoginPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    List<LoginPassword> selectByExample(LoginPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    LoginPassword selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoginPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_login_password
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginPassword record);
}