package com.bill99.mam.platform.persistence.dao;

import com.bill99.mam.platform.persistence.entity.OrderProductItem;
import com.bill99.mam.platform.persistence.entity.OrderProductItemExample;
import java.util.List;

public interface OrderProductItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    int insert(OrderProductItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    int insertSelective(OrderProductItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    List<OrderProductItem> selectByExample(OrderProductItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    OrderProductItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderProductItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order_productitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderProductItem record);
}