package com.bill99.mam.platform.persistence.dao;

import java.util.List;

import com.bill99.mam.platform.persistence.entity.Order;
import com.bill99.mam.platform.persistence.entity.OrderExample;
import com.bill99.mam.platform.service.model.request.OrderListReq;

public interface OrderExtMapper {
	List<Order> selectPageList(OrderListReq qryVo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_order
     *
     * @mbg.generated
     */
	Long countByExample(OrderExample example);
}