package com.bill99.mam.platform.persistence.dao;

import com.bill99.mam.platform.persistence.entity.Refund;
import com.bill99.mam.platform.persistence.entity.RefundExample;

import java.util.List;

public interface RefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long refundNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    int insert(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    int insertSelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    List<Refund> selectByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    Refund selectByPrimaryKey(Long refundNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mock_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Refund record);
}