package com.bill99.mam.platform.common.enumeration;

import org.apache.commons.lang3.StringUtils;

public enum PersonalBankEnum {
    ABC("ABC", "中国农业银行"),
    ACHMCB("ACHMCB", "廊坊市安次区惠民村镇银行"),
    AHRCU("AHRCU", "安徽省农村信用社联合社"),
    AYB("AYB", "安阳市商业银行"),
    BCOM("BCOM", "交通银行"),
    BDB("BDB", "保定银行"),
    BDHRCB("BDHRCB", "保德县慧融村镇银行"),
    BEA("BEA", "东亚银行"),
    BHDSCB("BHDSCB", "天津滨海德商村镇银行"),
    BHRCB("BHRCB", "天津滨海农村商业银行"),
    BHXFCB("BHXFCB", "盐城滨海兴福村镇银行"),
    BJRCB("BJRCB", "北京农商银行"),
    BOB("BOB", "北京银行"),
    BOC("BOC", "中国银行"),
    BQD("BQD", "青岛银行"),
    BSB("BSB", "包商银行"),
    CAB("CAB", "长安银行"),
    CBHB("CBHB", "渤海银行"),
    CCB("CCB", "中国建设银行"),
    CDRCB("CDRCB", "成都农村商业银行"),
    CEB("CEB", "中国光大银行"),
    CIB("CIB", "兴业银行"),
    CITI("CITI", "花旗银行"),
    CITIC("CITIC", "中信银行"),
    CMB("CMB", "招商银行"),
    CMBC("CMBC", "中国民生银行"),
    CMRCB("CMRCB", "上海崇明沪农商村镇银行"),
    CQB("CQB", "重庆银行"),
    CQRCB("CQRCB", "重庆农村商业银行"),
    CQTGB("CQTGB", "重庆三峡银行"),
    CSB("CSB", "长沙银行"),
    CSRCB("CSRCB", "常熟农村商业银行"),
    CYB("CYB", "朝阳银行"),
    CZB("CZB", "浙商银行"),
    CZCCB("CZCCB", "沧州银行"),
    DAHMCB("DAHMCB", "大安惠民村镇银行"),
    DBHMCB("DBHMCB", "荆门东宝惠民村镇银行"),
    DBS("DBS", "星展银行"),
    DHDSCB("DHDSCB", "浙江定海德商村镇银行"),
    DLB("DLB", "大连银行"),
    DYB("DYB", "东营银行"),
    DYRHCB("DYRHCB", "东营融和村镇银行"),
    DZB("DZB", "德州银行"),
    FDB("FDB", "富滇银行"),
    FGZYCB("FGZYCB", "扶沟郑银村镇银行"),
    FJRCC("FJRCC", "福建省农村信用社联合社"),
    GDB("GDB", "广发银行"),
    GDRCC("GDRCC", "广东省农村信用合作社"),
    GGXFCB("GGXFCB", "泰州高港兴福村镇银行"),
    GLB("GLB", "桂林银行"),
    GTQRCB("GTQRCB", "高唐青隆村镇银行"),
    GYB("GYB", "贵阳银行"),
    GYCB("GYCB", "固阳包商惠农村镇银行"),
    GZCB("GZCB", "广州银行"),
    GZRCC("GZRCC", "广州农村信用合作社联合社"),
    HBB("HBB", "河北银行"),
    HBCB("HBCB", "湖北银行"),
    HBRCC("HBRCC", "湖北农信社"),
    HDB("HDB", "邯郸市商业银行"),
    HEUCC("HEUCC", "鹤壁市城市信用社"),
    HFB("HFB", "恒丰银行"),
    HJDSCB("HJDSCB", "海宁德商村镇银行"),
    HNRCC("HNRCC", "湖南农村信用社联合社"),
    HNRCU("HNRCU", "海南省农村信用社联合社"),
    HRBB("HRBB", "哈尔滨银行"),
    HRBBZCB("HRBBZCB", "哈尔滨宾洲村镇银行"),
    HRJRCC("HRJRCC", "黑龙江省农村信用社联合社"),
    HSB("HSB", "徽商银行"),
    HSBC("HSBC", "汇丰银行"),
    HSCB("HSCB", "衡水市商业银行"),
    HSHMCB("HSHMCB", "含山惠民村镇银行"),
    HXB("HXB", "华夏银行"),
    HYXFCB("HYXFCB", "淮安淮阴兴福村镇银行"),
    HZB("HZB", "杭州银行"),
    ICBC("ICBC", "中国工商银行"),
    IMB("IMB", "内蒙古银行"),
    IMRCC("IMRCC", "内蒙古自治区农村信用社联合社"),
    JCB("JCB", "晋城商业银行"),
    JJB("JJB", "九江银行"),
    JLRCB("JLRCB", "吉林农信联合社"),
    JNRCB("JNRCB", "江南农村商业银行"),
    JSB("JSB", "江苏银行"),
    JSRCU("JSRCU", "江苏省农村信用社联合社"),
    JTLJCB("JTLJCB", "九台龙嘉村镇银行"),
    JXB("JXB", "嘉兴银行"),
    JXRCC("JXRCC", "江西农信联合社"),
    JYRCB("JYRCB", "江苏江阴农村商业银行"),
    JZB("JZB", "锦州银行"),
    JZCCB("JZCCB", "晋中市商业银行"),
    KEQCB("KEQCB", "科尔沁包商村镇银行"),
    KLB("KLB", "昆仑银行"),
    KSLCCB("KSLCCB", "昆山鹿城村镇银行"),
    KSRCB("KSRCB", "昆山农信社"),
    LJB("LJB", "龙江银行"),
    LPRXCB("LPRXCB", "乐平融兴村镇银行"),
    LPSYCB("LPSYCB", "滦平盛阳村镇银行"),
    LSCB("LSCB", "莱商银行"),
    LSCCB("LSCCB", "乐山市商业银行"),
    LSHMCB("LSHMCB", "庐江惠民村镇银行"),
    LZB("LZB", "柳州银行"),
    MZSYCB("MZSYCB", "孟州射阳村镇银行"),
    NBCB("NBCB", "宁波银行"),
    NCB("NCB", "江西银行"),
    NCCB("NCCB", "南充市商业银行"),
    NGHMCB("NGHMCB", "长春南关惠民村镇银行"),
    NJCB("NJCB", "南京银行"),
    NLDSCB("NLDSCB", "宁陵德商村镇银行"),
    NXB("NXB", "宁夏银行"),
    ORDOSB("ORDOSB", "鄂尔多斯银行"),
    PAB("PAB", "平安银行"),
    PDHMCB("PDHMCB", "青岛平度惠民村镇银行"),
    PSBC("PSBC", "中国邮政储蓄银行"),
    PZHCCB("PZHCCB", "攀枝花市商业银行"),
    QAHMCB("QAHMCB", "乾安惠民村镇银行"),
    QHB("QHB", "青海银行"),
    QHDCCB("QHDCCB", "秦皇岛银行"),
    QLB("QLB", "齐鲁银行"),
    QNB("QNB", "陕西秦农农村商业银行"),
    QPXFCBC("QPXFCBC", "淮安清浦兴福村镇银行"),
    QZB("QZB", "泉州银行"),
    SCB("SCB", "渣打银行"),
    SCXFCB("SCXFCB", "宿迁宿城兴福村镇银行"),
    SDRCB("SDRCB", "顺德农村商业银行"),
    SDRCC("SDRCC", "山东农村信用联合社"),
    SHB("SHB", "上海银行"),
    SHDWCB("SHDWCB", "江苏泗洪东吴村镇银行"),
    SJB("SJB", "盛京银行"),
    SNCCB("SNCCB", "遂宁市商业银行"),
    SPDB("SPDB", "浦发银行"),
    SRB("SRB", "上饶银行"),
    SRCB("SRCB", "上海农村商业银行"),
    SXRCC("SXRCC", "山西省农村信用社联合社"),
    SYDWCB("SYDWCB", "江苏宿豫东吴村镇银行"),
    SZRCB("SZRCB", "深圳农联社"),
    TACCB("TACCB", "泰安市商业银行"),
    TCRCB("TCRCB", "太仓农村商业银行"),
    TGXTCB("TGXTCB", "太谷县兴泰村镇银行"),
    TLB("TLB", "铁岭银行"),
    TSCCB("TSCCB", "唐山市商业银行"),
    TZB("TZB", "台州银行"),
    UCCB("UCCB", "乌鲁木齐银行"),
    WCHMCB("WCHMCB", "五常惠民村镇银行"),
    WFB("WFB", "潍坊银行"),
    WHB("WHB", "乌海银行"),
    WHCCB("WHCCB", "威海市商业银行"),
    WHRCB("WHRCB", "武汉农村商业银行"),
    WJRCB("WJRCB", "吴江农村商业银行"),
    WSQCB("WSQCB", "乌审旗包商村镇银行"),
    WXRCB("WXRCB", "无锡农村商业银行"),
    WZB("WZB", "温州银行"),
    XDGCCB("XDGCCB", "新都桂城村镇银行"),
    XHRHCB("XHRHCB", "襄垣县融汇村镇银行"),
    XTB("XTB", "邢台银行"),
    XXRHCB("XXRHCB", "献县融和村镇银行"),
    XZDSCB("XZDSCB", "浙江秀洲德商村镇银行"),
    YACCB("YACCB", "雅安市商业银行"),
    YDRCB("YDRCB", "尧都农村商业银行"),
    YKB("YKB", "营口银行"),
    YQCCB("YQCCB", "阳泉市商业银行"),
    YTB("YTB", "烟台银行"),
    YZB("YZB", "鄞州银行"),
    ZGCB("ZGCB", "自贡市商业银行"),
    ZGEQCB("ZGEQCB", "准格尔旗包商村镇银行"),
    ZHRCB("ZHRCB", "珠海农村商业银行"),
    ZJCZCB("ZJCZCB", "浙江稠州商业银行"),
    ZJGRCB("ZJGRCB", "张家港农村商业银行"),
    ZJKCCB("ZJKCCB", "张家口市商业银行"),
    ZJMTCB("ZJMTCB", "浙江民泰商业银行"),
    ZJTLCB("ZJTLCB", "浙江泰隆商业银行"),
    ZKCB("ZKCB", "周口市商业银行"),
    ZYCCB("ZYCCB", "遵义市商业银行");

    private String code;
    private String bankName;
    PersonalBankEnum(String code, String bankName){
        this.code = code;
        this.bankName = bankName;
    }

    public String getCode() {
        return code;
    }

    public String getBankName() {
        return bankName;
    }

    /**
     * 获取银行名字
     * @param code
     * @return
     */
    public static String name(String code){
        String bankName = "";
        for (PersonalBankEnum bank: values()) {
            if (StringUtils.equals(code, bank.getCode())){
                bankName = bank.getBankName();
                break;
            }
        }
        return bankName;
    }
}
